{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Long rod"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "didn't work for 54\n",
      "didn't work for 56\n",
      "didn't work for 58\n",
      "didn't work for 60\n",
      "didn't work for 62\n",
      "didn't work for 64\n",
      "didn't work for 66\n",
      "didn't work for 68\n"
     ]
    }
   ],
   "source": [
    "import win32com.client as wc\n",
    "\n",
    "def node_sketch(x, y, oTG, pw):\n",
    "    p = (-1)**pw\n",
    "    centre = oTG.CreatePoint2d(p*x, -y)\n",
    "    p1 = oTG.CreatePoint2d(p*(x-.36), -(y-.36))\n",
    "    p2 = oTG.CreatePoint2d(p*(x-.16), -(y-.16))\n",
    "    p3 = oTG.CreatePoint2d(p*(x+.16), -(y-.16))\n",
    "    p4 = oTG.CreatePoint2d(p*(x+.36), -(y-.36))\n",
    "    return centre, p1, p2, p3, p4\n",
    "def draw_sketch(centre, p1, p2, p3, p4, oSketch):\n",
    "    oSketch.SketchLines.AddAsTwoPointCenteredRectangle(centre, p2)\n",
    "    oLines1 = oSketch.SketchLines.AddByTwoPoints(p1, p2)\n",
    "    oLines2 = oSketch.SketchLines.AddByTwoPoints(oLines1.EndSketchPoint, p3)\n",
    "    oLines3 = oSketch.SketchLines.AddByTwoPoints(oLines2.EndSketchPoint, p4)\n",
    "    oLines4 = oSketch.SketchLines.AddByTwoPoints(oLines3.EndSketchPoint, oLines1.StartSketchPoint)\n",
    "def rotate(Sketch, oApp, angle):\n",
    "    objCollection = oApp.TransientObjects.CreateObjectCollection()\n",
    "    angle = angle * (3.141592653589793 / 180)\n",
    "    for line in Sketch.SketchLines:\n",
    "        objCollection.Add(line)\n",
    "    for line in Sketch.SketchArcs:\n",
    "        objCollection.Add(line)\n",
    "    Sketch.RotateSketchObjects(objCollection, oApp.TransientGeometry.CreatePoint2d(0, 0), angle)\n",
    "\n",
    "def combiner(l):\n",
    "    oApp = wc.GetActiveObject('Inventor.Application')\n",
    "    oPartDoc = oApp.Documents.Add(12290, oApp.FileManager.GetTemplateFile(12290, 8962, 9729, \"{9C464203-9BAE-11D3-8BAD-0060B0CE6BB4}\"))\n",
    "    oSketch = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(3))\n",
    "    oTG = oApp.TransientGeometry\n",
    "\n",
    "#draing the rod with curves\n",
    "    #lower profile\n",
    "    P1 = oTG.CreatePoint2d(0, 0)\n",
    "    P2 = oTG.CreatePoint2d(-0.07, 0)\n",
    "    P3 = oTG.CreatePoint2d(-0.07, 1.65)\n",
    "    P4 = oTG.CreatePoint2d(0.0809, 2.4259)\n",
    "    P5 = oTG.CreatePoint2d(.5116, 3.0886)\n",
    "    P6 = oTG.CreatePoint2d(3.5480, 6.23)\n",
    "    P7 = oTG.CreatePoint2d(4.1073, 7.7240)\n",
    "    P8 = oTG.CreatePoint2d(3.3959, 9.1518)\n",
    "    P9 = oTG.CreatePoint2d(-.1809, 12.1546)\n",
    "    P10 = oTG.CreatePoint2d(-.8824 , 13.3473)\n",
    "    P11 = oTG.CreatePoint2d(-.6757, 14.7155)\n",
    "    P12 = oTG.CreatePoint2d(-.3060, 15.4075)\n",
    "    P13 = oTG.CreatePoint2d(-.1299, 15.8642)\n",
    "    P14 = oTG.CreatePoint2d(-0.07, 16.35)\n",
    "    P15 = oTG.CreatePoint2d(-0.07, 17)\n",
    "    P16 = oTG.CreatePoint2d(0, 17)\n",
    "    #upper profile\n",
    "    P17 = oTG.CreatePoint2d(0, 16.35)\n",
    "    P18 = oTG.CreatePoint2d(-0.0620, 15.8472)   \n",
    "    P19 = oTG.CreatePoint2d(-.2443, 15.3745)\n",
    "    P20 = oTG.CreatePoint2d(-.6140, 14.6825)\n",
    "    P21 = oTG.CreatePoint2d(-.8137, 13.3606)\n",
    "    P22 = oTG.CreatePoint2d(-.1359, 12.2082)\n",
    "    P23 = oTG.CreatePoint2d(3.4409 , 9.2054)\n",
    "    P24 = oTG.CreatePoint2d(4.1772, 7.7276)\n",
    "    P25 = oTG.CreatePoint2d(3.5984, 6.1814)\n",
    "    P26 = oTG.CreatePoint2d(.5620, 3.04)\n",
    "    P27 = oTG.CreatePoint2d(.1458 , 2.3996)\n",
    "    P28 = oTG.CreatePoint2d(0, 1.65)\n",
    "    \n",
    "    oArc = oSketch.SketchArcs\n",
    "    oLines = oSketch.SketchLines\n",
    "\n",
    "    oLines1 = oLines.AddByTwoPoints(P1, P2)\n",
    "    oLines2 = oLines.AddByTwoPoints(oLines1.EndSketchPoint, P3)\n",
    "    oArc1 = oArc.AddByThreePoints(oLines2.EndSketchPoint, P4, P5)\n",
    "    oLines3 = oLines.AddByTwoPoints(oArc1.StartSketchPoint, P6)\n",
    "    oArc2 = oArc.AddByThreePoints(oLines3.EndSketchPoint, P7, P8)\n",
    "    oLines4 = oLines.AddByTwoPoints(oArc2.EndSketchPoint, P9)\n",
    "    oArc3 = oArc.AddByThreePoints(oLines4.EndSketchPoint, P10, P11)\n",
    "    oLines5 = oLines.AddByTwoPoints(oArc3.StartSketchPoint, P12)\n",
    "    oArc4 = oArc.AddByThreePoints(oLines5.EndSketchPoint, P13, P14)\n",
    "    oLines6 = oLines.AddByTwoPoints(oArc4.EndSketchPoint, P15)\n",
    "    oLines7 = oLines.AddByTwoPoints(oLines6.EndSketchPoint, P16)\n",
    "    oLines8 = oLines.AddByTwoPoints(oLines7.EndSketchPoint, P17)\n",
    "    oArc5 = oArc.AddByThreePoints(oLines8.EndSketchPoint, P18, P19)\n",
    "    oLines9 = oLines.AddByTwoPoints(oArc5.StartSketchPoint, P20)\n",
    "    oArc6 = oArc.AddByThreePoints(oLines9.EndSketchPoint, P21, P22)\n",
    "    oLines10 = oLines.AddByTwoPoints(oArc6.EndSketchPoint, P23)\n",
    "    oArc7 = oArc.AddByThreePoints(oLines10.EndSketchPoint, P24, P25)\n",
    "    oLines11 = oLines.AddByTwoPoints(oArc7.StartSketchPoint, P26)\n",
    "    oArc8 = oArc.AddByThreePoints(oLines11.EndSketchPoint, P27, P28)\n",
    "    oLines12 = oLines.AddByTwoPoints(oArc8.EndSketchPoint, oLines1.StartSketchPoint)\n",
    "    rotate(oSketch, oApp, 90)\n",
    "    oProfile = oSketch.Profiles.AddForSolid()\n",
    "    oExtFeature = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, l, 20995, 20481)\n",
    "\n",
    "    oApp.ActiveView.GoHome()\n",
    "    \n",
    "    num_notches = int((l-1)/50) + 1\n",
    "    division_len = (l-1)/num_notches\n",
    "\n",
    "#making notches in the rod\n",
    "    oFace1 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(12)\n",
    "    oEdge1 = oFace1.Edges.Item(1)\n",
    "    oVertex1 = oEdge1.StartVertex\n",
    "    oSketch1 = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(oFace1, oEdge1, True, True, oVertex1)\n",
    "    for i in range(num_notches):\n",
    "        x, y = .5 + i*division_len, .36\n",
    "        centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 2)\n",
    "        draw_sketch(centre, p1, p2, p3, p4, oSketch1)\n",
    "    x, y = l-.5, .36\n",
    "    centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 2)\n",
    "    draw_sketch(centre, p1, p2, p3, p4, oSketch1)\n",
    "\n",
    "    oFace2 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(20)\n",
    "    oEdge2 = oFace2.Edges.Item(2)\n",
    "    oVertex2 = oEdge2.StartVertex\n",
    "    oSketch2 = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(oFace2, oEdge2, True, False, oVertex2)\n",
    "    for i in range(num_notches):\n",
    "        x, y = .5 + i*division_len, .36\n",
    "        centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 3)\n",
    "        draw_sketch(centre, p1, p2, p3, p4, oSketch2)\n",
    "    x, y = l-.5, .36\n",
    "    centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 3)\n",
    "    draw_sketch(centre, p1, p2, p3, p4, oSketch2)\n",
    "\n",
    "    solid_profile1 = oSketch2.Profiles.AddforSolid()\n",
    "    ext_solid_def1 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def1.SetDistanceExtent(0.07, 20994)\n",
    "\n",
    "    solid_profile1 = oSketch1.Profiles.AddforSolid()\n",
    "    ext_solid_def2 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def2.SetDistanceExtent(0.07, 20994)\n",
    "\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def1)\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def2)\n",
    "\n",
    "    list1 = [3, 4, 5, 21, 23, 26]\n",
    "    for k in range(1, 71):\n",
    "        try:\n",
    "            f = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(k)\n",
    "            e = f.Edges.Item(1)\n",
    "            oVertex2 = e.StartVertex\n",
    "            s = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(f, e, True, True, oVertex2)\n",
    "            s.Name = f\"Sketch-unfold-{k}\"\n",
    "        except:\n",
    "            print(f\"didn't work for {k}\")\n",
    "        # k=3, 4, 5, 21, 23, 26 \n",
    "\n",
    "#k=8, 9, 10, 22, 23, 49, 52, 5, 61\n",
    "#total faces is equal to 70\n",
    "# i = 2, 10, 20, 12\n",
    "#height_input = float(input(\"Enter height: \"))\n",
    "length = 147\n",
    "combiner(length)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# upper offset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "didn't work for 3\n",
      "didn't work for 5\n",
      "didn't work for 7\n",
      "didn't work for 9\n",
      "didn't work for 11\n",
      "didn't work for 13\n",
      "didn't work for 15\n",
      "didn't work for 17\n",
      "didn't work for 19\n",
      "didn't work for 21\n",
      "didn't work for 23\n",
      "didn't work for 25\n"
     ]
    }
   ],
   "source": [
    "import win32com.client as wc\n",
    "\n",
    "def combiner(h, k):\n",
    "    oApp = wc.GetActiveObject('Inventor.Application')\n",
    "\n",
    "    oPartDoc = oApp.Documents.Add(12290, oApp.FileManager.GetTemplateFile(12290, 8962))\n",
    "\n",
    "    oSketch = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(3))\n",
    "\n",
    "    oTG = oApp.TransientGeometry\n",
    "\n",
    "    #lower profile\n",
    "    P1 = oTG.CreatePoint2d(0, 0.3)\n",
    "    P2 = oTG.CreatePoint2d(0.0879 , 0.0879)\n",
    "    P3 = oTG.CreatePoint2d(0.3, 0)\n",
    "\n",
    "    P4 = oTG.CreatePoint2d(1.9121, -0.0458)\n",
    "    P5 = oTG.CreatePoint2d(2.2577, -0.1806)\n",
    "    P6 = oTG.CreatePoint2d(1.544, 0)\n",
    "\n",
    "    P7 = oTG.CreatePoint2d(4.3794, -.7908)\n",
    "    P8 = oTG.CreatePoint2d(2.9869, -.5751)\n",
    "    P9 = oTG.CreatePoint2d(5.5947, -0.0778)\n",
    "\n",
    "    P10 = oTG.CreatePoint2d(10.0204 , 4.2073)\n",
    "    P11 = oTG.CreatePoint2d(8.5929, 3.4955)\n",
    "    P12 = oTG.CreatePoint2d(11.5145, 3.6485)\n",
    "\n",
    "    P13 = oTG.CreatePoint2d(15.3653, 0.182)\n",
    "    P14 = oTG.CreatePoint2d(14.5651, .7018)\n",
    "    P15 = oTG.CreatePoint2d(16.3020, 0)\n",
    "\n",
    "    P16 = oTG.CreatePoint2d(18.4121, 0.0879)\n",
    "    P17 = oTG.CreatePoint2d(18.2, 0)\n",
    "    P18 = oTG.CreatePoint2d(18.5, .3)\n",
    "\n",
    "    #upper profile\n",
    "    P19 = oTG.CreatePoint2d(0.0879, 2.3221+h)\n",
    "    P20 = oTG.CreatePoint2d(.3, 2.41+h)\n",
    "    P21 = oTG.CreatePoint2d(0, 2.1100+h)\n",
    "\n",
    "    P22 = oTG.CreatePoint2d(1.8856, 2.3337+h)\n",
    "    P23 = oTG.CreatePoint2d(2.4609 , 2.1097+h)\n",
    "    P24 = oTG.CreatePoint2d(1.2730, 2.4100+h)\n",
    "\n",
    "    P25 = oTG.CreatePoint2d(4.4022, 1.5725+h)\n",
    "    P26 = oTG.CreatePoint2d(3.0766, 1.7772+h)\n",
    "    P27 = oTG.CreatePoint2d(5.5590 , 2.2514+h)\n",
    "\n",
    "    P28 = oTG.CreatePoint2d(10.0282, 6.5381+h)\n",
    "    P29 = oTG.CreatePoint2d(8.5294, 5.7909+h)\n",
    "    P30 = oTG.CreatePoint2d(11.5968, 5.9516+h)\n",
    "\n",
    "    P31 = oTG.CreatePoint2d(15.3081, 2.5192+h)\n",
    "    P32 = oTG.CreatePoint2d(14.8280, 2.8310+h)\n",
    "    P33 = oTG.CreatePoint2d(15.8700, 2.4100+h)\n",
    "\n",
    "    P34 = oTG.CreatePoint2d(18.4121 , 2.3221+h)\n",
    "    P35 = oTG.CreatePoint2d(18.5 , 2.11+h)\n",
    "    P36 = oTG.CreatePoint2d(18.2, 2.41+h)\n",
    "\n",
    "    oArc = oSketch.SketchArcs\n",
    "    oLines = oSketch.SketchLines\n",
    "    \n",
    "    oArc1 = oArc.AddByThreePoints(P1, P2, P3)\n",
    "    oLines1 = oLines.AddByTwoPoints(oArc1.EndSketchPoint, P6)\n",
    "    oArc2 = oArc.AddByThreePoints(oLines1.EndSketchPoint, P4, P5)\n",
    "    oLines2 = oLines.AddByTwoPoints(oArc2.StartSketchPoint, P8)\n",
    "    oArc3 = oArc.AddByThreePoints(oLines2.EndSketchPoint, P7, P9)\n",
    "    oLines3 = oLines.AddByTwoPoints(oArc3.EndSketchPoint, P11)\n",
    "    oArc4 = oArc.AddByThreePoints(oLines3.EndSketchPoint, P10, P12)\n",
    "    oLines4 = oLines.AddByTwoPoints(oArc4.StartSketchPoint, P14)\n",
    "    oArc5 = oArc.AddByThreePoints(oLines4.EndSketchPoint, P13, P15)\n",
    "    oLines5 = oLines.AddByTwoPoints(oArc5.EndSketchPoint, P17)\n",
    "    oArc6 = oArc.AddByThreePoints(oLines5.EndSketchPoint, P16, P18)\n",
    "    oLines6 = oLines.AddByTwoPoints(oArc1.StartSketchPoint, P21)\n",
    "    oArc7 = oArc.AddByThreePoints(oLines6.EndSketchPoint, P19, P20)\n",
    "    oLines7 = oLines.AddByTwoPoints(oArc7.StartSketchPoint, P24)\n",
    "    oArc8 = oArc.AddByThreePoints(oLines7.EndSketchPoint, P22, P23)\n",
    "    oLines8 = oLines.AddByTwoPoints(oArc8.StartSketchPoint, P26)\n",
    "    oArc9 = oArc.AddByThreePoints(oLines8.EndSketchPoint, P25, P27)\n",
    "    oLines9 = oLines.AddByTwoPoints(oArc9.EndSketchPoint, P29)\n",
    "    oArc10 = oArc.AddByThreePoints(oLines9.EndSketchPoint, P28, P30)\n",
    "    oLines10 = oLines.AddByTwoPoints(oArc10.StartSketchPoint, P32)\n",
    "    oArc11 = oArc.AddByThreePoints(oLines10.EndSketchPoint, P31, P33)\n",
    "    oLines11 = oLines.AddByTwoPoints(oArc11.EndSketchPoint, P36)\n",
    "    oArc12 = oArc.AddByThreePoints(oLines11.EndSketchPoint, P34, P35)\n",
    "    oLines12 = oLines.AddByTwoPoints(oArc12.StartSketchPoint, oArc6.EndSketchPoint)\n",
    "\n",
    "    oProfile = oSketch.Profiles.AddForSolid()\n",
    "    oExtFeature = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, 0.05, 20995, 20481)\n",
    "\n",
    "    oApp.ActiveView.GoHome()\n",
    "\n",
    "    for k in range(1,27):\n",
    "        try:\n",
    "            f = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(k)\n",
    "            e = f.Edges.Item(1)\n",
    "            oVertex2 = e.StartVertex\n",
    "            s = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(f, e, True, True, oVertex2)\n",
    "            s.Name = f\"Sketch-unfold-{k}\"\n",
    "        except:\n",
    "            print(f\"didn't work for {k}\")    \n",
    "    #k = 6, 3, 4, 26, 3\n",
    "profile_offset = 1.195\n",
    "actual_offset = 2.41 #this should as this as it is points of these are refered from the offset profile\n",
    "\n",
    "combiner(profile_offset - actual_offset, 0)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# binder"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "didn't work for 1\n",
      "didn't work for 4\n",
      "didn't work for 6\n",
      "didn't work for 9\n",
      "didn't work for 11\n",
      "didn't work for 14\n",
      "didn't work for 15\n",
      "didn't work for 16\n",
      "didn't work for 17\n",
      "didn't work for 18\n",
      "didn't work for 19\n"
     ]
    }
   ],
   "source": [
    "import win32com.client as wc\n",
    "\n",
    "def rotate(Sketch, oApp, angle):\n",
    "    objCollection = oApp.TransientObjects.CreateObjectCollection()\n",
    "    angle = angle * (3.141592653589793 / 180)\n",
    "    for line in Sketch.SketchLines:\n",
    "        objCollection.Add(line)\n",
    "    for line in Sketch.SketchArcs:\n",
    "        objCollection.Add(line)\n",
    "    Sketch.RotateSketchObjects(objCollection, oApp.TransientGeometry.CreatePoint2d(0, 0), angle)\n",
    "def combiner(h):\n",
    "    oApp = wc.GetActiveObject('Inventor.Application')\n",
    "\n",
    "    oPartDoc = oApp.Documents.Add(12290, oApp.FileManager.GetTemplateFile(12290, 8962))\n",
    "\n",
    "    oSketch = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(2))\n",
    "\n",
    "    oTG = oApp.TransientGeometry\n",
    "\n",
    "    oSkPnts = oSketch.SketchPoints\n",
    "    #inner circle\n",
    "    oSkPnts.Add(oTG.CreatePoint2d(0, 0), False)     #1\n",
    "    oSkPnts.Add(oTG.CreatePoint2d(0, -0.05), False) #2\n",
    "    oSkPnts.Add(oTG.CreatePoint2d(0, 0.05), False)  #3\n",
    "    #outer circle\n",
    "    oSkPnts.Add(oTG.CreatePoint2d(0, -0.15), False) #4\n",
    "    oSkPnts.Add(oTG.CreatePoint2d(0, 0.15), False)  #5\n",
    "    #inner line\n",
    "    oSkPnts.Add(oTG.CreatePoint2d(-1.35, -0.05), False) #6\n",
    "    oSkPnts.Add(oTG.CreatePoint2d(-1.35, 0.05), False)  #7\n",
    "    #outer line\n",
    "    oSkPnts.Add(oTG.CreatePoint2d(-1.35, -0.15), False) #8\n",
    "    oSkPnts.Add(oTG.CreatePoint2d(-1.35, 0.15), False)  #9\n",
    "\n",
    "    oArc = oSketch.SketchArcs\n",
    "    oArc1 = oArc.AddByCenterStartEndPoint(oSkPnts(1), oSkPnts(2), oSkPnts(3))\n",
    "    oArc2 = oArc.AddByCenterStartEndPoint(oSkPnts(1), oSkPnts(4), oSkPnts(5))\n",
    "\n",
    "    oLines = oSketch.SketchLines\n",
    "    oLine1 = oLines.AddByTwoPoints(oSkPnts(6), oSkPnts(2))\n",
    "    oLine2 = oLines.AddByTwoPoints(oSkPnts(7), oSkPnts(3))\n",
    "    oLine3 = oLines.AddByTwoPoints(oSkPnts(8), oSkPnts(4))\n",
    "    oLine4 = oLines.AddByTwoPoints(oSkPnts(9), oSkPnts(5))\n",
    "    oLine5 = oLines.AddByTwoPoints(oSkPnts(6), oSkPnts(8))\n",
    "    oLine6 = oLines.AddByTwoPoints(oSkPnts(7), oSkPnts(9))\n",
    "\n",
    "    #rotate(oSketch, oApp, 180)\n",
    "\n",
    "    oProfile = oSketch.Profiles.AddForSolid()\n",
    "    oExtFeature = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, h, 20995, 20481)\n",
    "\n",
    "    edge1 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(3).Edges.Item(2)\n",
    "    edge2 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(3).Edges.Item(4)\n",
    "    edge3 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(7).Edges.Item(2)\n",
    "    edge4 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(7).Edges.Item(4)\n",
    "\n",
    "    edge_collection = oApp.TransientObjects.CreateEdgeCollection()\n",
    "    fillet_def = oPartDoc.ComponentDefinition.Features.FilletFeatures.CreateFilletDefinition()\n",
    "\n",
    "    edge_collection.Add(edge1)\n",
    "    edge_collection.Add(edge2)\n",
    "    edge_collection.Add(edge3)\n",
    "    edge_collection.Add(edge4)\n",
    "\n",
    "    fillet_def.AddConstantRadiusEdgeSet(edge_collection, 0.1)\n",
    "    oPartDoc.ComponentDefinition.Features.FilletFeatures.Add(fillet_def)\n",
    "\n",
    "    oApp.ActiveView.GoHome()\n",
    "    \n",
    "    for k in range(1,20):\n",
    "        try:\n",
    "            f = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(k)\n",
    "            e = f.Edges.Item(1)\n",
    "            oVertex2 = e.StartVertex\n",
    "            s = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(f, e, True, True, oVertex2)\n",
    "            s.Name = f\"Sketch-unfold-{k}\"\n",
    "        except:\n",
    "            print(f\"didn't work for {k}\")\n",
    "\n",
    "#height_input = float(input(\"Enter height: \"))\n",
    "\n",
    "combiner(5)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# offset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "didn't work for 3\n",
      "didn't work for 5\n",
      "didn't work for 7\n",
      "didn't work for 9\n",
      "didn't work for 11\n",
      "didn't work for 13\n",
      "didn't work for 15\n",
      "didn't work for 17\n",
      "didn't work for 19\n",
      "didn't work for 21\n",
      "didn't work for 23\n",
      "didn't work for 25\n"
     ]
    }
   ],
   "source": [
    "import win32com.client as wc\n",
    "\n",
    "def combiner(h):\n",
    "    oApp = wc.GetActiveObject('Inventor.Application')\n",
    "\n",
    "    oPartDoc = oApp.Documents.Add(12290, oApp.FileManager.GetTemplateFile(12290, 8962))\n",
    "\n",
    "    oSketch = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(3))\n",
    "\n",
    "    oTG = oApp.TransientGeometry\n",
    "\n",
    "    #lower profile\n",
    "    P1 = oTG.CreatePoint2d(0, 0.3)\n",
    "    P2 = oTG.CreatePoint2d(0.0879 , 0.0879)\n",
    "    P3 = oTG.CreatePoint2d(0.3, 0)\n",
    "\n",
    "    P4 = oTG.CreatePoint2d(1.9121, -0.0458)\n",
    "    P5 = oTG.CreatePoint2d(2.2577, -0.1806)\n",
    "    P6 = oTG.CreatePoint2d(1.544, 0)\n",
    "\n",
    "    P7 = oTG.CreatePoint2d(4.3794, -.7908)\n",
    "    P8 = oTG.CreatePoint2d(2.9869, -.5751)\n",
    "    P9 = oTG.CreatePoint2d(5.5947, -0.0778)\n",
    "\n",
    "    P10 = oTG.CreatePoint2d(10.0204 , 4.2073)\n",
    "    P11 = oTG.CreatePoint2d(8.5929, 3.4955)\n",
    "    P12 = oTG.CreatePoint2d(11.5145, 3.6485)\n",
    "\n",
    "    P13 = oTG.CreatePoint2d(15.3653, 0.182)\n",
    "    P14 = oTG.CreatePoint2d(14.5651, .7018)\n",
    "    P15 = oTG.CreatePoint2d(16.3020, 0)\n",
    "\n",
    "    P16 = oTG.CreatePoint2d(18.4121, 0.0879)\n",
    "    P17 = oTG.CreatePoint2d(18.2, 0)\n",
    "    P18 = oTG.CreatePoint2d(18.5, .3)\n",
    "\n",
    "    #upper profile\n",
    "    P19 = oTG.CreatePoint2d(0.0879, 2.3221+h)\n",
    "    P20 = oTG.CreatePoint2d(.3, 2.41+h)\n",
    "    P21 = oTG.CreatePoint2d(0, 2.1100+h)\n",
    "\n",
    "    P22 = oTG.CreatePoint2d(1.8856, 2.3337+h)\n",
    "    P23 = oTG.CreatePoint2d(2.4609 , 2.1097+h)\n",
    "    P24 = oTG.CreatePoint2d(1.2730, 2.4100+h)\n",
    "\n",
    "    P25 = oTG.CreatePoint2d(4.4022, 1.5725+h)\n",
    "    P26 = oTG.CreatePoint2d(3.0766, 1.7772+h)\n",
    "    P27 = oTG.CreatePoint2d(5.5590 , 2.2514+h)\n",
    "\n",
    "    P28 = oTG.CreatePoint2d(10.0282, 6.5381+h)\n",
    "    P29 = oTG.CreatePoint2d(8.5294, 5.7909+h)\n",
    "    P30 = oTG.CreatePoint2d(11.5968, 5.9516+h)\n",
    "\n",
    "    P31 = oTG.CreatePoint2d(15.3081, 2.5192+h)\n",
    "    P32 = oTG.CreatePoint2d(14.8280, 2.8310+h)\n",
    "    P33 = oTG.CreatePoint2d(15.8700, 2.4100+h)\n",
    "\n",
    "    P34 = oTG.CreatePoint2d(18.4121 , 2.3221+h)\n",
    "    P35 = oTG.CreatePoint2d(18.5 , 2.11+h)\n",
    "    P36 = oTG.CreatePoint2d(18.2, 2.41+h)\n",
    "\n",
    "    oArc = oSketch.SketchArcs\n",
    "    oLines = oSketch.SketchLines\n",
    "    \n",
    "    oArc1 = oArc.AddByThreePoints(P1, P2, P3)#\n",
    "    oLines1 = oLines.AddByTwoPoints(oArc1.EndSketchPoint, P6)\n",
    "    oArc2 = oArc.AddByThreePoints(oLines1.EndSketchPoint, P4, P5)\n",
    "    oLines2 = oLines.AddByTwoPoints(oArc2.StartSketchPoint, P8)\n",
    "    oArc3 = oArc.AddByThreePoints(oLines2.EndSketchPoint, P7, P9)\n",
    "    oLines3 = oLines.AddByTwoPoints(oArc3.EndSketchPoint, P11)\n",
    "    oArc4 = oArc.AddByThreePoints(oLines3.EndSketchPoint, P10, P12)\n",
    "    oLines4 = oLines.AddByTwoPoints(oArc4.StartSketchPoint, P14)\n",
    "    oArc5 = oArc.AddByThreePoints(oLines4.EndSketchPoint, P13, P15)\n",
    "    oLines5 = oLines.AddByTwoPoints(oArc5.EndSketchPoint, P17)\n",
    "    oArc6 = oArc.AddByThreePoints(oLines5.EndSketchPoint, P16, P18)\n",
    "    oLines6 = oLines.AddByTwoPoints(oArc1.StartSketchPoint, P21)\n",
    "    oArc7 = oArc.AddByThreePoints(oLines6.EndSketchPoint, P19, P20)\n",
    "    oLines7 = oLines.AddByTwoPoints(oArc7.StartSketchPoint, P24)\n",
    "    oArc8 = oArc.AddByThreePoints(oLines7.EndSketchPoint, P22, P23)\n",
    "    oLines8 = oLines.AddByTwoPoints(oArc8.StartSketchPoint, P26)\n",
    "    oArc9 = oArc.AddByThreePoints(oLines8.EndSketchPoint, P25, P27)\n",
    "    oLines9 = oLines.AddByTwoPoints(oArc9.EndSketchPoint, P29)\n",
    "    oArc10 = oArc.AddByThreePoints(oLines9.EndSketchPoint, P28, P30)\n",
    "    oLines10 = oLines.AddByTwoPoints(oArc10.StartSketchPoint, P32)\n",
    "    oArc11 = oArc.AddByThreePoints(oLines10.EndSketchPoint, P31, P33)\n",
    "    oLines11 = oLines.AddByTwoPoints(oArc11.EndSketchPoint, P36)\n",
    "    oArc12 = oArc.AddByThreePoints(oLines11.EndSketchPoint, P34, P35)\n",
    "    oLines12 = oLines.AddByTwoPoints(oArc12.StartSketchPoint, oArc6.EndSketchPoint)\n",
    "    oProfile = oSketch.Profiles.AddForSolid()\n",
    "    oExtFeature = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, 0.05, 20995, 20481)\n",
    "    oApp.ActiveView.GoHome()\n",
    "\n",
    "    for k in range(1,27):\n",
    "        try:\n",
    "            f = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(k)\n",
    "            e = f.Edges.Item(1)\n",
    "            oVertex2 = e.StartVertex\n",
    "            s = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(f, e, True, True, oVertex2)\n",
    "            s.Name = f\"Sketch-unfold-{k}\"\n",
    "        except:\n",
    "            print(f\"didn't work for {k}\")\n",
    "\n",
    "#height_input = float(input(\"Enter height: \"))\n",
    "profile_offset = 2.41 #will be taken as an input\n",
    "actual_offset = 2.41\n",
    "\n",
    "combiner(profile_offset - actual_offset)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
