{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# final code for assembly (need some optimization)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import win32com.client as wc\n",
    "\n",
    "profile_offset = 2.41 #will be taken as an input\n",
    "offset_prof = profile_offset + 0.02 + 0.07 #profile_offset + 0.07 + 0.02(for tolerance)\n",
    "num_profile = 15\n",
    "offset_prof2 = 47.9467 + .72\n",
    "\n",
    "oApp = wc.GetActiveObject('Inventor.Application')\n",
    "oAssyDoc  = oApp.Documents.Add(12291, oApp.FileManager.GetTemplateFile(12291, 8962))\n",
    "oAxisDef = oApp.ActiveDocument.ComponentDefinition\n",
    "oDef = oAssyDoc.ComponentDefinition\n",
    "oXAxis = oDef.WorkAxes.Item(1)\n",
    "oYAxis = oDef.WorkAxes.Item(2)\n",
    "oZAxis = oDef.WorkAxes.Item(3)\n",
    "\n",
    "oPositionMatrix = oApp.TransientGeometry.CreateMatrix()\n",
    "sFileName = r\"C:\\Users\\usaid\\Downloads\\lechler_project\\project_code\\rectangular_piece_components\\Long_rod.ipt\"\n",
    "rod = oAssyDoc.ComponentDefinition.Occurrences.Add(sFileName, oPositionMatrix)\n",
    "\n",
    "sFileName = r\"C:\\Users\\usaid\\Downloads\\lechler_project\\project_code\\rectangular_piece_components\\Offset.ipt\"\n",
    "offset = oAssyDoc.ComponentDefinition.Occurrences.Add(sFileName, oPositionMatrix)\n",
    "\n",
    "sFileName = r\"C:\\Users\\usaid\\Downloads\\lechler_project\\project_code\\rectangular_piece_components\\upper_offset.ipt\"\n",
    "upper_offset_down = oAssyDoc.ComponentDefinition.Occurrences.Add(sFileName, oPositionMatrix)\n",
    "upper_offset_up = oAssyDoc.ComponentDefinition.Occurrences.AddByComponentDefinition(upper_offset_down.Definition, oPositionMatrix)\n",
    "\n",
    "sFileName = r\"C:\\Users\\usaid\\Downloads\\lechler_project\\project_code\\rectangular_piece_components\\Binder.ipt\"\n",
    "binder_left = oAssyDoc.ComponentDefinition.Occurrences.Add(sFileName, oPositionMatrix)\n",
    "binder_right = oAssyDoc.ComponentDefinition.Occurrences.AddByComponentDefinition(binder_left.Definition, oPositionMatrix)\n",
    "\n",
    "#mate 6\n",
    "face1 = rod.SurfaceBodies(1).Faces.Item(26)\n",
    "face2 = upper_offset_down.SurfaceBodies(1).Faces.Item(4)\n",
    "oAxisDef.Constraints.AddMateConstraint(face1, face2, \"0.1 mm\", 24833, 24833)\n",
    "\n",
    "#flush 5\n",
    "face1 = offset.SurfaceBodies(1).Faces.Item(26)\n",
    "face2 = upper_offset_down.SurfaceBodies(1).Faces.Item(26)\n",
    "oAxisDef.Constraints.AddFlushConstraint(face1, face2, \"0 mm\")\n",
    "\n",
    "#flush 6\n",
    "face1 = offset.SurfaceBodies(1).Faces.Item(2)\n",
    "face2 = upper_offset_down.SurfaceBodies(1).Faces.Item(2)\n",
    "oAxisDef.Constraints.AddFlushConstraint(face1, face2, \"0 mm\")\n",
    "\n",
    "#flush 7\n",
    "face1 = binder_left.SurfaceBodies(1).Faces.Item(2)\n",
    "face2 = upper_offset_down.SurfaceBodies(1).Faces.Item(24)\n",
    "oAxisDef.Constraints.AddFlushConstraint(face1, face2, \"1.5 mm\")\n",
    "\n",
    "#mate 8\n",
    "face1 = binder_left.SurfaceBodies(1).Faces.Item(3)\n",
    "face2 = upper_offset_down.SurfaceBodies(1).Faces.Item(1)\n",
    "oAxisDef.Constraints.AddMateConstraint(face1, face2, \"0 mm\")\n",
    "\n",
    "#mate 7\n",
    "face1 = binder_left.SurfaceBodies(1).Faces.Item(13)\n",
    "face2 = rod.SurfaceBodies(1).Faces.Item(5)\n",
    "oAxisDef.Constraints.AddMateConstraint(face1, face2, \"0.2 mm\")\n",
    "\n",
    "#flush 8\n",
    "face1 = binder_left.SurfaceBodies(1).Faces.Item(2)\n",
    "face2 = binder_right.SurfaceBodies(1).Faces.Item(2)\n",
    "oAxisDef.Constraints.AddFlushConstraint(face1, face2, \"0 mm\")\n",
    "\n",
    "#flush 9\n",
    "face1 = binder_left.SurfaceBodies(1).Faces.Item(10)\n",
    "face2 = binder_right.SurfaceBodies(1).Faces.Item(12)\n",
    "oAxisDef.Constraints.AddFlushConstraint(face1, face2, \"0 mm\")\n",
    "\n",
    "#mate 9\n",
    "face1 = binder_right.SurfaceBodies(1).Faces.Item(7)\n",
    "face2 = rod.SurfaceBodies(1).Faces.Item(31)  ############ needs to parametrise\n",
    "oAxisDef.Constraints.AddMateConstraint(face1, face2, \"0.2 mm\")\n",
    "\n",
    "#creating pattern for long rod\n",
    "oParentOccs_rod = oApp.TransientObjects.CreateObjectCollection()\n",
    "oParentOccs_rod.Add(oDef.Occurrences.Item(1))\n",
    "oRectOccPattern_rod = oDef.OccurrencePatterns.AddRectangularPattern(oParentOccs_rod, oXAxis, True, 0, 1, oYAxis, True, offset_prof, num_profile)\n",
    "#creating pattern for offset\n",
    "oParentOccs_offset = oApp.TransientObjects.CreateObjectCollection()\n",
    "oParentOccs_offset.Add(oDef.Occurrences.Item(1))\n",
    "oRectOccPattern_offset = oDef.OccurrencePatterns.AddRectangularPattern(oParentOccs_offset, oXAxis, True, 0, 1, oYAxis, True, offset_prof, num_profile-1)\n",
    "\n",
    "#flush 10\n",
    "element = oRectOccPattern_offset.OccurrencePatternElement(num_profile-2, 1).Occurrences.Item(1)\n",
    "face1 = element.SurfaceBodies(1).Faces.Item(2)\n",
    "face2 = upper_offset_up.SurfaceBodies(1).Faces.Item(2)\n",
    "oAxisDef.Constraints.AddFlushConstraint(face1, face2, \"0 mm\")\n",
    "\n",
    "#flush 11\n",
    "face1 = element.SurfaceBodies(1).Faces.Item(24)\n",
    "face2 = upper_offset_up.SurfaceBodies(1).Faces.Item(24)\n",
    "oAxisDef.Constraints.AddFlushConstraint(face1, face2, \"-50 mm\")\n",
    "\n",
    "#flush 12\n",
    "face1 = element.SurfaceBodies(1).Faces.Item(26)\n",
    "face2 = upper_offset_up.SurfaceBodies(1).Faces.Item(26)\n",
    "oAxisDef.Constraints.AddFlushConstraint(face1, face2, \"0 mm\")\n",
    "\n",
    "#mate 3\n",
    "element = oRectOccPattern_rod.OccurrencePatternElement(2, 1).Occurrences.Item(1)\n",
    "face1 = element.SurfaceBodies(1).Faces.Item(26)\n",
    "face2 = offset.SurfaceBodies(1).Faces.Item(4)\n",
    "oAxisDef.Constraints.AddMateConstraint(face1, face2, \"0.1 mm\")\n",
    "\n",
    "#mate 4\n",
    "face1 = element.SurfaceBodies(1).Faces.Item(4)\n",
    "face2 = offset.SurfaceBodies(1).Faces.Item(26)\n",
    "oAxisDef.Constraints.AddMateConstraint(face1, face2, \"1.1 mm\")\n",
    "\n",
    "#flush 2\n",
    "face1 = element.SurfaceBodies(1).Faces.Item(21)\n",
    "face2 = offset.SurfaceBodies(1).Faces.Item(2)\n",
    "oAxisDef.Constraints.AddFlushConstraint(face1, face2, \"7.5 mm\")\n",
    "\n",
    "oParentOccs_com = oApp.TransientObjects.CreateObjectCollection()\n",
    "oParentOccs_com1 = oApp.TransientObjects.CreateObjectCollection()\n",
    "oParentOccs_com.Add(oDef.Occurrences.Item(1))\n",
    "oParentOccs_com.Add(oDef.Occurrences.Item(2))\n",
    "oParentOccs_com.Add(oDef.Occurrences.Item(3))\n",
    "oParentOccs_com.Add(oDef.Occurrences.Item(4))\n",
    "oParentOccs_com.Add(oRectOccPattern_offset.OccurrencePatternElements.Parent)\n",
    "oRectOccPattern_com = oDef.OccurrencePatterns.AddRectangularPattern(oParentOccs_com, oXAxis, True, 0, 1, oZAxis, True, -offset_prof2, 2)\n",
    "\n",
    "oParentOccs_com = oApp.TransientObjects.CreateObjectCollection()\n",
    "oParentOccs_com.Add(oRectOccPattern_com.OccurrencePatternElements.Parent)\n",
    "oRectOccPattern_com = oDef.OccurrencePatterns.AddRectangularPattern(oParentOccs_com, oXAxis, True, 0, 1, oZAxis, True, 2*offset_prof2, 2)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "-> when number of notches is even it takes the notch 1 as the second last notch opposite side of origin\n",
    "-> when ts odd it take last notch as notch 1\n",
    "-> k = (num_notches+1)*5 + 1\n",
    "-> k = (num_notches+1)*5 + 1 + num_notches + 2\n",
    "\n",
    "k = 3, 4, 5, 21, 23, 26 \n",
    "\n",
    "k = (num_notches+1)*5 + 1, (num_notches+1)*5 + 1 + num_notches + 2   {for 21 and 26 respectively}\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "selectedOccurrence = part_component_definition.Occurrences.Item(1)  \n",
    "\n",
    "-> Access the component definition of the selected occurrence\n",
    "\n",
    "compDef = selectedOccurrence.Definition\n",
    "\n",
    "-> Get the work planes collection of the selected component\n",
    "\n",
    "workPlanes = compDef.WorkPlanes.Item(3)\n",
    "\n",
    "print(workPlanes.Name)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Description \n",
    "\n",
    "Method that returns the specified OccurrencePattern object from the collection.\n",
    "\n",
    "Syntax \n",
    "OccurrencePatterns.Item( Index As Variant )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#this is an example of assembling\n",
    "import win32com.client as wc\n",
    "\n",
    "oApp = wc.GetActiveObject('Inventor.Application')\n",
    "\n",
    "oAssyDoc  = oApp.Documents.Add(12291, oApp.FileManager.GetTemplateFile(12291, 8962))\n",
    "\n",
    "part_com_definition = oAssyDoc.ComponentDefinition\n",
    "\n",
    "sketch = part_com_definition.Sketches.Add(part_com_definition.WorkPlanes.Item(3))\n",
    "\n",
    "tg = oApp.TransientGeometry\n",
    "\n",
    "oPositionMatrix = oApp.TransientGeometry.CreateMatrix()\n",
    "sFileName = r\"C:\\Users\\usaid\\Downloads\\lechler_project\\project_code\\cylinder.ipt\"\n",
    "oCylinder1 = oAssyDoc.ComponentDefinition.Occurrences.Add(sFileName, oPositionMatrix)\n",
    "\"\"\"oTrans = oApp.TransientGeometry.CreateVector(.2, 0, -.1)\n",
    "oPositionMatrix.SetTranslation(oTrans)\"\"\"\n",
    "oCylinder2 = oAssyDoc.ComponentDefinition.Occurrences.AddByComponentDefinition(oCylinder1.Definition, oPositionMatrix)\n",
    "\n",
    "oAxisDef = oApp.ActiveDocument.ComponentDefinition\n",
    "\n",
    "workPlanes_1_xy = oCylinder1.Definition.WorkPlanes.Item(3)\n",
    "print(workPlanes_1_xy.Name)\n",
    "\n",
    "workPlanes_2_xy = oCylinder2.Definition.WorkPlanes.Item(3)\n",
    "print(workPlanes_2_xy.Name)\n",
    "\n",
    "\n",
    "\n",
    "oAsmPlane1 = oCylinder1.CreateGeometryProxy(workPlanes_1_xy)\n",
    "oAsmPlane2 = oCylinder2.CreateGeometryProxy(workPlanes_2_xy)\n",
    "dst = 50\n",
    "oConstr = oAxisDef.Constraints.AddMateConstraint(oAsmPlane1, oAsmPlane2, f\"{dst} mm\", 24833, 24833)\n",
    "\n",
    "oCylAxis1, oCylAxis2 = 0, 0\n",
    "\n",
    "\"\"\"#putting axis of both cylinders at some distance\n",
    "for oFace in oCylinder1.SurfaceBodies(1).Faces:\n",
    "    if(oFace.SurfaceType == 5891):   #kCylinderSurface\n",
    "       oCylAxis1 = oFace\n",
    "for oFace in oCylinder2.SurfaceBodies(1).Faces:\n",
    "    if(oFace.SurfaceType == 5891):   #kCylinderSurface\n",
    "       oCylAxis2 = oFace\n",
    "\n",
    "oConstr = oAxisDef.Constraints.AddMateConstraint(oCylAxis1, oCylAxis2, 0, 24834, 24834)\n",
    "\n",
    "oCylFace1, oCylFace2 = 0, 0\n",
    "\n",
    "for oFace in oCylinder1.SurfaceBodies(1).Faces:\n",
    "    if(oFace.SurfaceType == 5890):  #kPlaneSurface\n",
    "       oCylFace1 = oFace\n",
    "for oFace in oCylinder2.SurfaceBodies(1).Faces:\n",
    "    if(oFace.SurfaceType == 5890):  #kPlaneSurface\n",
    "       oCylFace1 = oFace\n",
    "\n",
    "face1 = oCylinder1.SurfaceBodies.Item(1).Faces.Item(3)\n",
    "face2 = oCylinder2.SurfaceBodies.Item(1).Faces.Item(3)\n",
    "\n",
    "oConstr = oAxisDef.Constraints.AddMateConstraint(face1, face2, \"0 mm\", 24833, 24833)\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#tis is an example of cutting sketches from the 3d model\n",
    "import win32com.client as wc\n",
    "\n",
    "inv = wc.GetActiveObject('Inventor.Application')\n",
    "print(inv)\n",
    "\n",
    "#create a part document\n",
    "inv_part_document = inv.Documents.Add(12290, inv.FileManager.GetTemplateFile(12290, 8962))\n",
    "#inv_part_document = inv.ActiveDocument\n",
    "#set a reference to the part component definition\n",
    "part_com_definition = inv_part_document.ComponentDefinition\n",
    "#create a sketch\n",
    "sketch = part_com_definition.Sketches.Add(part_com_definition.WorkPlanes.Item(3))\n",
    "\n",
    "tg = inv.TransientGeometry\n",
    "\n",
    "sketch.SketchLines.AddAsTwoPointCenteredRectangle(tg.CreatePoint2d(0,0), tg.CreatePoint2d(8,3))\n",
    "\n",
    "inv.ActiveView.GoHome()\n",
    "\n",
    "#create an extrusion\n",
    "solid_profile = sketch.Profiles.AddforSolid()\n",
    "\n",
    "#height\n",
    "h = 1\n",
    "\n",
    "#creating the feature\n",
    "ext_solid_def = part_com_definition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile, 20481)\n",
    "ext_solid_def.SetDistanceExtent(1, 20994)\n",
    "part_com_definition.Features.ExtrudeFeatures.Add(ext_solid_def)\n",
    "\n",
    "oFace = part_com_definition.SurfaceBodies.Item(1).Faces.Item(1)\n",
    "oEdge = oFace.Edges.Item(1)\n",
    "oVertex = oEdge.StartVertex\n",
    "oSketch = part_com_definition.Sketches.AddWithOrientation(oFace, oEdge, False, True, oVertex)\n",
    "\n",
    "#oSketch = part_com_definition.Sketches.Add(oFace)\n",
    "oSketch.SketchLines.AddAsTwoPointCenteredRectangle(tg.CreatePoint2d(0, 0), tg.CreatePoint2d(.2, .3))\n",
    "\n",
    "solid_profile1 = oSketch.Profiles.AddforSolid()\n",
    "ext_solid_def1 = part_com_definition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "ext_solid_def1.SetDistanceExtent(1, 20994)\n",
    "part_com_definition.Features.ExtrudeFeatures.Add(ext_solid_def1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#tis is an example of cutting sketches from the 3d model\n",
    "\n",
    "import win32com.client as wc\n",
    "\n",
    "inv = wc.GetActiveObject('Inventor.Application')\n",
    "print(inv)\n",
    "\n",
    "#create a part document\n",
    "inv_part_document = inv.Documents.Add(12290, inv.FileManager.GetTemplateFile(12290, 8962))\n",
    "#inv_part_document = inv.ActiveDocument\n",
    "#set a reference to the part component definition\n",
    "part_com_definition = inv_part_document.ComponentDefinition\n",
    "#create a sketch\n",
    "sketch = part_com_definition.Sketches.Add(part_com_definition.WorkPlanes.Item(3))\n",
    "\n",
    "tg = inv.TransientGeometry\n",
    "\n",
    "sketch.SketchLines.AddAsTwoPointCenteredRectangle(tg.CreatePoint2d(0,0), tg.CreatePoint2d(8,3))\n",
    "\n",
    "inv.ActiveView.GoHome()\n",
    "\n",
    "#create an extrusion\n",
    "solid_profile = sketch.Profiles.AddforSolid()\n",
    "\n",
    "#height\n",
    "h = 1\n",
    "\n",
    "#creating the feature\n",
    "ext_solid_def = part_com_definition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile, 20481)\n",
    "ext_solid_def.SetDistanceExtent(1, 20994)\n",
    "part_com_definition.Features.ExtrudeFeatures.Add(ext_solid_def)\n",
    "\n",
    "\n",
    "oFace = part_com_definition.SurfaceBodies.Item(1).Faces.Item(1)\n",
    "oSketch = part_com_definition.Sketches.Add(oFace)\n",
    "oSketch.SketchLines.AddAsTwoPointCenteredRectangle(tg.CreatePoint2d(.5, 3), tg.CreatePoint2d(.7053, 2.7029))\n",
    "\n",
    "solid_profile1 = oSketch.Profiles.AddforSolid()\n",
    "ext_solid_def1 = part_com_definition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "ext_solid_def1.SetDistanceExtent(1, 20994)\n",
    "part_com_definition.Features.ExtrudeFeatures.Add(ext_solid_def1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#example how to select workplane of an object, use mate function, flush function\n",
    "#workplane selection\n",
    "workPlanes_rod_xy = rod.Definition.WorkPlanes.Item(3)\n",
    "workPlanes_rod_yz = rod.Definition.WorkPlanes.Item(1)\n",
    "\n",
    "workPlanes_upper_xy = upper_offset.Definition.WorkPlanes.Item(3)\n",
    "\n",
    "workPlanes_binder_yz = binder.Definition.WorkPlanes.Item(1)\n",
    "\n",
    "#mate 1\n",
    "dis = -239.733 - 3.6 #length of rod / 2\n",
    "oAsmPlane1 = rod.CreateGeometryProxy(workPlanes_rod_xy)\n",
    "oAsmPlane2 = upper_offset.CreateGeometryProxy(workPlanes_upper_xy)\n",
    "oAxisDef.Constraints.AddMateConstraint(oAsmPlane1, oAsmPlane2, f\"{dis} mm\", 24833, 24833)\n",
    "\n",
    "#flush1\n",
    "oAsmPlane1 = rod.CreateGeometryProxy(workPlanes_rod_yz)\n",
    "oAsmPlane2 = binder.CreateGeometryProxy(workPlanes_binder_yz)\n",
    "oAxisDef.Constraints.AddFlushConstraint(oAsmPlane1, oAsmPlane2, \"0\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
