{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import win32com.client as wc\n",
    "\n",
    "def node_sketch(x, y, oTG, pw):\n",
    "    p = (-1)**pw\n",
    "    centre = oTG.CreatePoint2d(p*x, -y)\n",
    "    p1 = oTG.CreatePoint2d(p*(x-.36), -(y-.36))\n",
    "    p2 = oTG.CreatePoint2d(p*(x-.16), -(y-.16))\n",
    "    p3 = oTG.CreatePoint2d(p*(x+.16), -(y-.16))\n",
    "    p4 = oTG.CreatePoint2d(p*(x+.36), -(y-.36))\n",
    "    return centre, p1, p2, p3, p4\n",
    "def draw_sketch(centre, p1, p2, p3, p4, oSketch):\n",
    "    oSketch.SketchLines.AddAsTwoPointCenteredRectangle(centre, p2)\n",
    "    oLines1 = oSketch.SketchLines.AddByTwoPoints(p1, p2)\n",
    "    oLines2 = oSketch.SketchLines.AddByTwoPoints(oLines1.EndSketchPoint, p3)\n",
    "    oLines3 = oSketch.SketchLines.AddByTwoPoints(oLines2.EndSketchPoint, p4)\n",
    "    oLines4 = oSketch.SketchLines.AddByTwoPoints(oLines3.EndSketchPoint, oLines1.StartSketchPoint)\n",
    "    \n",
    "\n",
    "def combiner(l):\n",
    "    oApp = wc.GetActiveObject('Inventor.Application')\n",
    "    oPartDoc = oApp.Documents.Add(12290, oApp.FileManager.GetTemplateFile(12290, 8962, 9729))\n",
    "    oSketch = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(3))\n",
    "    oTG = oApp.TransientGeometry\n",
    "\n",
    "#draing the rod with curves\n",
    "\n",
    "    #lower profile\n",
    "    P1 = oTG.CreatePoint2d(0, 0)\n",
    "    P2 = oTG.CreatePoint2d(-0.07, 0)\n",
    "    P3 = oTG.CreatePoint2d(-0.07, 1.65)\n",
    "    P4 = oTG.CreatePoint2d(0.0809, 2.4259)\n",
    "    P5 = oTG.CreatePoint2d(.5116, 3.0886)\n",
    "    P6 = oTG.CreatePoint2d(3.5480, 6.23)\n",
    "    P7 = oTG.CreatePoint2d(4.1073, 7.7240)\n",
    "    P8 = oTG.CreatePoint2d(3.3959, 9.1518)\n",
    "    P9 = oTG.CreatePoint2d(-.1809, 12.1546)\n",
    "    P10 = oTG.CreatePoint2d(-.8824 , 13.3473)\n",
    "    P11 = oTG.CreatePoint2d(-.6757, 14.7155)\n",
    "    P12 = oTG.CreatePoint2d(-.3060, 15.4075)\n",
    "    P13 = oTG.CreatePoint2d(-.1299, 15.8642)\n",
    "    P14 = oTG.CreatePoint2d(-0.07, 16.35)\n",
    "    P15 = oTG.CreatePoint2d(-0.07, 17)\n",
    "    P16 = oTG.CreatePoint2d(0, 17)\n",
    "    #upper profile\n",
    "    P17 = oTG.CreatePoint2d(0, 16.35)\n",
    "    P18 = oTG.CreatePoint2d(-0.0620, 15.8472)   \n",
    "    P19 = oTG.CreatePoint2d(-.2443, 15.3745)\n",
    "    P20 = oTG.CreatePoint2d(-.6140, 14.6825)\n",
    "    P21 = oTG.CreatePoint2d(-.8137, 13.3606)\n",
    "    P22 = oTG.CreatePoint2d(-.1359, 12.2082)\n",
    "    P23 = oTG.CreatePoint2d(3.4409 , 9.2054)\n",
    "    P24 = oTG.CreatePoint2d(4.1772, 7.7276)\n",
    "    P25 = oTG.CreatePoint2d(3.5984, 6.1814)\n",
    "    P26 = oTG.CreatePoint2d(.5620, 3.04)\n",
    "    P27 = oTG.CreatePoint2d(.1458 , 2.3996)\n",
    "    P28 = oTG.CreatePoint2d(0, 1.65)\n",
    "    \n",
    "    oArc = oSketch.SketchArcs\n",
    "    oLines = oSketch.SketchLines\n",
    "\n",
    "    oLines1 = oLines.AddByTwoPoints(P1, P2)\n",
    "    oLines2 = oLines.AddByTwoPoints(oLines1.EndSketchPoint, P3)\n",
    "    oArc1 = oArc.AddByThreePoints(oLines2.EndSketchPoint, P4, P5)\n",
    "    oLines3 = oLines.AddByTwoPoints(oArc1.StartSketchPoint, P6)\n",
    "    oArc2 = oArc.AddByThreePoints(oLines3.EndSketchPoint, P7, P8)\n",
    "    oLines4 = oLines.AddByTwoPoints(oArc2.EndSketchPoint, P9)\n",
    "    oArc3 = oArc.AddByThreePoints(oLines4.EndSketchPoint, P10, P11)\n",
    "    oLines5 = oLines.AddByTwoPoints(oArc3.StartSketchPoint, P12)\n",
    "    oArc4 = oArc.AddByThreePoints(oLines5.EndSketchPoint, P13, P14)\n",
    "    oLines6 = oLines.AddByTwoPoints(oArc4.EndSketchPoint, P15)\n",
    "    oLines7 = oLines.AddByTwoPoints(oLines6.EndSketchPoint, P16)\n",
    "    oLines8 = oLines.AddByTwoPoints(oLines7.EndSketchPoint, P17)\n",
    "    oArc5 = oArc.AddByThreePoints(oLines8.EndSketchPoint, P18, P19)\n",
    "    oLines9 = oLines.AddByTwoPoints(oArc5.StartSketchPoint, P20)\n",
    "    oArc6 = oArc.AddByThreePoints(oLines9.EndSketchPoint, P21, P22)\n",
    "    oLines10 = oLines.AddByTwoPoints(oArc6.EndSketchPoint, P23)\n",
    "    oArc7 = oArc.AddByThreePoints(oLines10.EndSketchPoint, P24, P25)\n",
    "    oLines11 = oLines.AddByTwoPoints(oArc7.StartSketchPoint, P26)\n",
    "    oArc8 = oArc.AddByThreePoints(oLines11.EndSketchPoint, P27, P28)\n",
    "    oLines12 = oLines.AddByTwoPoints(oArc8.EndSketchPoint, oLines1.StartSketchPoint)\n",
    "\n",
    "    oProfile = oSketch.Profiles.AddForSolid()\n",
    "    oExtFeature = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, l, 20995, 20481)\n",
    "\n",
    "    oApp.ActiveView.GoHome()\n",
    "    \n",
    "    num_notches = int((l-1)/50) + 1\n",
    "    division_len = (l-1)/num_notches\n",
    "\n",
    "#making notches in the rod\n",
    "\n",
    "    oFace1 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(12)\n",
    "    oEdge1 = oFace1.Edges.Item(1)\n",
    "    oVertex1 = oEdge1.StartVertex\n",
    "    oSketch1 = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(oFace1, oEdge1, True, True, oVertex1)\n",
    "    for i in range(num_notches):\n",
    "        x, y = .5 + i*division_len, .36\n",
    "        centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 2)\n",
    "        draw_sketch(centre, p1, p2, p3, p4, oSketch1)\n",
    "    x, y = l-.5, .36\n",
    "    centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 2)\n",
    "    draw_sketch(centre, p1, p2, p3, p4, oSketch1)\n",
    "\n",
    "    oFace2 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(20)\n",
    "    oEdge2 = oFace2.Edges.Item(2)\n",
    "    oVertex2 = oEdge2.StartVertex\n",
    "    oSketch2 = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(oFace2, oEdge2, True, False, oVertex2)\n",
    "    for i in range(num_notches):\n",
    "        x, y = .5 + i*division_len, .36\n",
    "        centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 3)\n",
    "        draw_sketch(centre, p1, p2, p3, p4, oSketch2)\n",
    "    x, y = l-.5, .36\n",
    "    centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 3)\n",
    "    draw_sketch(centre, p1, p2, p3, p4, oSketch2)\n",
    "\n",
    "    solid_profile1 = oSketch2.Profiles.AddforSolid()\n",
    "    ext_solid_def1 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def1.SetDistanceExtent(0.07, 20994)\n",
    "\n",
    "    solid_profile1 = oSketch1.Profiles.AddforSolid()\n",
    "    ext_solid_def2 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def2.SetDistanceExtent(0.07, 20994)\n",
    "\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def1)\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def2)\n",
    "\n",
    "#cutting the rod to fit the curved shape\n",
    "\n",
    "    z0, x0 = l/2 + 76.5, 320\n",
    "    sketch_xz = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(2))\n",
    "    sketch_xz.SketchCircles.AddByCenterRadius(oTG.CreatePoint2d(-x0, -z0), 372.9)\n",
    "    sketch_xz.SketchCircles.AddByCenterRadius(oTG.CreatePoint2d(-x0, -z0), 500)\n",
    "    solid_profile1 = sketch_xz.Profiles.AddforSolid()\n",
    "    ext_solid_def1 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def1.SetDistanceExtent(17, 20993)\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def1)\n",
    "\n",
    "#drawing a sketch to cut the slant side\n",
    "    \"\"\"oSketch3D = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(1))\n",
    "    x1, z1 = -.07, 49.8364 #z needs to be edited\n",
    "    #oTG.CreatePoint( , , )\n",
    "    # sketch a line =     oLine = oSketch3D.SketchLines3D.AddByTwoPoints( , )\n",
    "    # sketch an arc =     oArc = oSketch3D.SketchArcs3D.AddByThreePoints( , , )\n",
    "    oLinestart = oSketch3D.SketchLines.AddByTwoPoints(oTG.CreatePoint2d(0, z1), oTG.CreatePoint2d(1.65, z1))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLinestart.EndSketchPoint, oTG.CreatePoint2d(3.0886, z1+.9696))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(6.2300, z1+5.9263))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(9.1518, z1+5.6820))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(12.1546, z1-.1856))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(14.7155, z1-1.0169))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(15.4075, z1-.3953))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(16.3500, z1))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(17, z1))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(17, z1+1))\n",
    "    z1 = 49.8364 + 1\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(16.3500, z1))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d( 15.4075, z1-.3953))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(14.7155, z1-1.0169))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(12.1546, z1-.1856))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(9.1518, z1+5.6820))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(6.2300, z1+5.9263))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(3.0886, z1+.9696))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(1.65, z1))\n",
    "    oLine = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint2d(0, z1))\n",
    "    oLineend = oSketch3D.SketchLines.AddByTwoPoints(oLine.EndSketchPoint, oLinestart.StartSketchPoint)\n",
    "\n",
    "    oProfile = oSketch3D.Profiles.AddForSolid()\n",
    "    oExtFeature = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, 100, 20995, 20482)\"\"\"\n",
    "    \n",
    "\n",
    "\n",
    "# i = 2, 10, 20, 12\n",
    "#height_input = float(input(\"Enter height: \"))\n",
    "length = 130\n",
    "combiner(length)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "oApp = wc.GetActiveObject('Inventor.Application')\n",
    "oPartDoc = oApp.Documents.Add(12290, oApp.FileManager.GetTemplateFile(12290, 8962, 9729))\n",
    "oSketch = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(3))\n",
    "oTG = oApp.TransientGeometry\n",
    "\n",
    "oSketch3D = oPartDoc.ComponentDefinition.Sketches3D.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(1))\n",
    "x1, z1 = -.07, 49.8364 #z needs to be edited\n",
    "#oTG.CreatePoint( , , )\n",
    "# sketch a line =     oLine = oSketch3D.SketchLines3D.AddByTwoPoints( , )\n",
    "# sketch an arc =     oArc = oSketch3D.SketchArcs3D.AddByThreePoints( , , )\n",
    "oLinestart = oSketch3D.SketchLines3D.AddByTwoPoints(oTG.CreatePoint(x1, 0, z1), oTG.CreatePoint(x1, 1.65, z1), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLinestart.EndSketchPoint, oTG.CreatePoint(.5816+x1, 3.0886, z1+.9696), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(3.6180+x1, 6.2300, z1+5.9263), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(3.4659+x1, 9.1518, z1+5.6820), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(-.1109+x1, 12.1546, z1-.1856), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(-.6057+x1, 14.7155, z1-1.0169), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(-.2360+x1, 15.4075, z1-.3953), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(x1, 16.3500, z1), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(x1, 17, z1), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(x1, 17, z1+1), False)\n",
    "z1 = 49.8364 + 1\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(x1, 16.3500, z1), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(-.2360+x1, 15.4075, z1-.3953), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(-.6057+x1, 14.7155, z1-1.0169), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(-.1109+x1, 12.1546, z1-.1856), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(3.4659+x1, 9.1518, z1+5.6820), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(3.6180+x1, 6.2300, z1+5.9263), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(.5816+x1, 3.0886, z1+.9696), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(x1, 1.65, z1), False)\n",
    "oLine = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oTG.CreatePoint(x1, 0, z1), False)\n",
    "oLineend = oSketch3D.SketchLines3D.AddByTwoPoints(oLine.EndSketchPoint, oLinestart.StartSketchPoint, False)\n",
    "\n",
    "\n",
    "\n",
    "\"\"\"oProfile = oSketch3D.Profiles.AddForSolid()\n",
    "oExtFeature = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, 1, 20995, 20481)\n",
    "\n",
    "oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(oExtFeature)\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import win32com.client as wc\n",
    "\n",
    "def node_sketch(x, y, oTG, pw):\n",
    "    p = (-1)**pw\n",
    "    centre = oTG.CreatePoint2d(p*x, -y)\n",
    "    p1 = oTG.CreatePoint2d(p*(x-.36), -(y-.36))\n",
    "    p2 = oTG.CreatePoint2d(p*(x-.16), -(y-.16))\n",
    "    p3 = oTG.CreatePoint2d(p*(x+.16), -(y-.16))\n",
    "    p4 = oTG.CreatePoint2d(p*(x+.36), -(y-.36))\n",
    "    return centre, p1, p2, p3, p4\n",
    "def draw_sketch(centre, p1, p2, p3, p4, oSketch):\n",
    "    oSketch.SketchLines.AddAsTwoPointCenteredRectangle(centre, p2)\n",
    "    oLines1 = oSketch.SketchLines.AddByTwoPoints(p1, p2)\n",
    "    oLines2 = oSketch.SketchLines.AddByTwoPoints(oLines1.EndSketchPoint, p3)\n",
    "    oLines3 = oSketch.SketchLines.AddByTwoPoints(oLines2.EndSketchPoint, p4)\n",
    "    oLines4 = oSketch.SketchLines.AddByTwoPoints(oLines3.EndSketchPoint, oLines1.StartSketchPoint)\n",
    "\n",
    "def combiner(l, k):\n",
    "    oApp = wc.GetActiveObject('Inventor.Application')\n",
    "    oPartDoc = oApp.Documents.Add(12290, oApp.FileManager.GetTemplateFile(12290, 8962, 9729, \"{9C464203-9BAE-11D3-8BAD-0060B0CE6BB4}\"))\n",
    "    oSketch = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(3))\n",
    "    oTG = oApp.TransientGeometry\n",
    "\n",
    "#draing the rod with curves\n",
    "\n",
    "    #lower profile\n",
    "    P1 = oTG.CreatePoint2d(0, 0)\n",
    "    P2 = oTG.CreatePoint2d(-0.07, 0)\n",
    "    P3 = oTG.CreatePoint2d(-0.07, 1.65)\n",
    "    P4 = oTG.CreatePoint2d(0.0809, 2.4259)\n",
    "    P5 = oTG.CreatePoint2d(.5116, 3.0886)\n",
    "    P6 = oTG.CreatePoint2d(3.5480, 6.23)\n",
    "    P7 = oTG.CreatePoint2d(4.1073, 7.7240)\n",
    "    P8 = oTG.CreatePoint2d(3.3959, 9.1518)\n",
    "    P9 = oTG.CreatePoint2d(-.1809, 12.1546)\n",
    "    P10 = oTG.CreatePoint2d(-.8824 , 13.3473)\n",
    "    P11 = oTG.CreatePoint2d(-.6757, 14.7155)\n",
    "    P12 = oTG.CreatePoint2d(-.3060, 15.4075)\n",
    "    P13 = oTG.CreatePoint2d(-.1299, 15.8642)\n",
    "    P14 = oTG.CreatePoint2d(-0.07, 16.35)\n",
    "    P15 = oTG.CreatePoint2d(-0.07, 17)\n",
    "    P16 = oTG.CreatePoint2d(0, 17)\n",
    "    #upper profile\n",
    "    P17 = oTG.CreatePoint2d(0, 16.35)\n",
    "    P18 = oTG.CreatePoint2d(-0.0620, 15.8472)   \n",
    "    P19 = oTG.CreatePoint2d(-.2443, 15.3745)\n",
    "    P20 = oTG.CreatePoint2d(-.6140, 14.6825)\n",
    "    P21 = oTG.CreatePoint2d(-.8137, 13.3606)\n",
    "    P22 = oTG.CreatePoint2d(-.1359, 12.2082)\n",
    "    P23 = oTG.CreatePoint2d(3.4409 , 9.2054)\n",
    "    P24 = oTG.CreatePoint2d(4.1772, 7.7276)\n",
    "    P25 = oTG.CreatePoint2d(3.5984, 6.1814)\n",
    "    P26 = oTG.CreatePoint2d(.5620, 3.04)\n",
    "    P27 = oTG.CreatePoint2d(.1458 , 2.3996)\n",
    "    P28 = oTG.CreatePoint2d(0, 1.65)\n",
    "    \n",
    "    oArc = oSketch.SketchArcs\n",
    "    oLines = oSketch.SketchLines\n",
    "\n",
    "    oLines1 = oLines.AddByTwoPoints(P1, P2)\n",
    "    oLines2 = oLines.AddByTwoPoints(oLines1.EndSketchPoint, P3)\n",
    "    oArc1 = oArc.AddByThreePoints(oLines2.EndSketchPoint, P4, P5)\n",
    "    oLines3 = oLines.AddByTwoPoints(oArc1.StartSketchPoint, P6)\n",
    "    oArc2 = oArc.AddByThreePoints(oLines3.EndSketchPoint, P7, P8)\n",
    "    oLines4 = oLines.AddByTwoPoints(oArc2.EndSketchPoint, P9)\n",
    "    oArc3 = oArc.AddByThreePoints(oLines4.EndSketchPoint, P10, P11)\n",
    "    oLines5 = oLines.AddByTwoPoints(oArc3.StartSketchPoint, P12)\n",
    "    oArc4 = oArc.AddByThreePoints(oLines5.EndSketchPoint, P13, P14)\n",
    "    oLines6 = oLines.AddByTwoPoints(oArc4.EndSketchPoint, P15)\n",
    "    oLines7 = oLines.AddByTwoPoints(oLines6.EndSketchPoint, P16)\n",
    "    oLines8 = oLines.AddByTwoPoints(oLines7.EndSketchPoint, P17)\n",
    "    oArc5 = oArc.AddByThreePoints(oLines8.EndSketchPoint, P18, P19)\n",
    "    oLines9 = oLines.AddByTwoPoints(oArc5.StartSketchPoint, P20)\n",
    "    oArc6 = oArc.AddByThreePoints(oLines9.EndSketchPoint, P21, P22)\n",
    "    oLines10 = oLines.AddByTwoPoints(oArc6.EndSketchPoint, P23)\n",
    "    oArc7 = oArc.AddByThreePoints(oLines10.EndSketchPoint, P24, P25)\n",
    "    oLines11 = oLines.AddByTwoPoints(oArc7.StartSketchPoint, P26)\n",
    "    oArc8 = oArc.AddByThreePoints(oLines11.EndSketchPoint, P27, P28)\n",
    "    oLines12 = oLines.AddByTwoPoints(oArc8.EndSketchPoint, oLines1.StartSketchPoint)\n",
    "\n",
    "    oProfile = oSketch.Profiles.AddForSolid()\n",
    "    oExtFeature = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, l, 20995, 20481)\n",
    "\n",
    "    oApp.ActiveView.GoHome()\n",
    "    \n",
    "    num_notches = int((l-1)/50) + 1\n",
    "    division_len = (l-1)/num_notches\n",
    "\n",
    "#making notches in the rod\n",
    "\n",
    "    \"\"\"oFace1 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(12)\n",
    "    oEdge1 = oFace1.Edges.Item(1)\n",
    "    oVertex1 = oEdge1.StartVertex\n",
    "    oSketch1 = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(oFace1, oEdge1, True, True, oVertex1)\n",
    "    for i in range(num_notches):\n",
    "        x, y = .5 + i*division_len, .36\n",
    "        centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 2)\n",
    "        draw_sketch(centre, p1, p2, p3, p4, oSketch1)\n",
    "    x, y = l-.5, .36\n",
    "    centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 2)\n",
    "    draw_sketch(centre, p1, p2, p3, p4, oSketch1)\n",
    "\n",
    "    oFace2 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(20)\n",
    "    oEdge2 = oFace2.Edges.Item(2)\n",
    "    oVertex2 = oEdge2.StartVertex\n",
    "    oSketch2 = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(oFace2, oEdge2, True, False, oVertex2)\n",
    "    for i in range(num_notches):\n",
    "        x, y = .5 + i*division_len, .36\n",
    "        centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 3)\n",
    "        draw_sketch(centre, p1, p2, p3, p4, oSketch2)\n",
    "    x, y = l-.5, .36\n",
    "    centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 3)\n",
    "    draw_sketch(centre, p1, p2, p3, p4, oSketch2)\n",
    "\n",
    "    solid_profile1 = oSketch2.Profiles.AddforSolid()\n",
    "    ext_solid_def1 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def1.SetDistanceExtent(0.07, 20994)\n",
    "\n",
    "    solid_profile1 = oSketch1.Profiles.AddforSolid()\n",
    "    ext_solid_def2 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def2.SetDistanceExtent(0.07, 20994)\n",
    "\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def1)\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def2)\"\"\"\n",
    "\n",
    "#cutting the rod to fit the curved shape\n",
    "\n",
    "    z0, x0 = l/2 + 76.5, 320\n",
    "    sketch_xz = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(2))\n",
    "    sketch_xz.SketchCircles.AddByCenterRadius(oTG.CreatePoint2d(-x0, -z0), 372.9)\n",
    "    sketch_xz.SketchCircles.AddByCenterRadius(oTG.CreatePoint2d(-x0, -z0), 500)\n",
    "    solid_profile1 = sketch_xz.Profiles.AddforSolid()\n",
    "    ext_solid_def1 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def1.SetDistanceExtent(17, 20993)\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def1)\n",
    "\n",
    "    try:\n",
    "        f = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(k)\n",
    "        e = f.Edges.Item(1)\n",
    "        oVertex2 = e.StartVertex\n",
    "        s = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(f, e, True, True, oVertex2)\n",
    "        s.Name = f\"Sketch-unfold-{k}\"\n",
    "    except:\n",
    "        print(f\"didn't work for {k}\")\n",
    "    #k = 2, 10, 13, 21\n",
    "    \n",
    "\n",
    "#unfolding\n",
    "    \"\"\"allFaces = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces\n",
    "    oFace1 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(20)\n",
    "    unfoldFeatures = oPartDoc.ComponentDefinition.Features.UnfoldFeatures.Add(oFace1)\n",
    "    oPartDoc.ComponentDefinition.Unfold()\"\"\"\n",
    "\n",
    "\n",
    "\n",
    "# i = 2, 10, 20, 12\n",
    "#height_input = float(input(\"Enter height: \"))\n",
    "length = 130\n",
    "for i in range(1,23):\n",
    "    combiner(length, i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import win32com.client as wc\n",
    "\n",
    "def node_sketch(x, y, oTG, pw):\n",
    "    p = (-1)**pw\n",
    "    centre = oTG.CreatePoint2d(p*x, -y)\n",
    "    p1 = oTG.CreatePoint2d(p*(x-.36), -(y-.36))\n",
    "    p2 = oTG.CreatePoint2d(p*(x-.16), -(y-.16))\n",
    "    p3 = oTG.CreatePoint2d(p*(x+.16), -(y-.16))\n",
    "    p4 = oTG.CreatePoint2d(p*(x+.36), -(y-.36))\n",
    "    return centre, p1, p2, p3, p4\n",
    "def draw_sketch(centre, p1, p2, p3, p4, oSketch):\n",
    "    oSketch.SketchLines.AddAsTwoPointCenteredRectangle(centre, p2)\n",
    "    oLines1 = oSketch.SketchLines.AddByTwoPoints(p1, p2)\n",
    "    oLines2 = oSketch.SketchLines.AddByTwoPoints(oLines1.EndSketchPoint, p3)\n",
    "    oLines3 = oSketch.SketchLines.AddByTwoPoints(oLines2.EndSketchPoint, p4)\n",
    "    oLines4 = oSketch.SketchLines.AddByTwoPoints(oLines3.EndSketchPoint, oLines1.StartSketchPoint)\n",
    "def rotate(Sketch, oApp, angle):\n",
    "    objCollection = oApp.TransientObjects.CreateObjectCollection()\n",
    "    angle = angle * (3.141592653589793 / 180)\n",
    "    for line in Sketch.SketchLines:\n",
    "        objCollection.Add(line)\n",
    "    for line in Sketch.SketchArcs:\n",
    "        objCollection.Add(line)\n",
    "    Sketch.RotateSketchObjects(objCollection, oApp.TransientGeometry.CreatePoint2d(0, 0), angle)\n",
    "\n",
    "def combiner(l, k):\n",
    "    oApp = wc.GetActiveObject('Inventor.Application')\n",
    "    oPartDoc = oApp.Documents.Add(12290, oApp.FileManager.GetTemplateFile(12290, 8962, 9729, \"{9C464203-9BAE-11D3-8BAD-0060B0CE6BB4}\"))\n",
    "    oSketch = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(3))\n",
    "    oTG = oApp.TransientGeometry\n",
    "\n",
    "#draing the rod with curves\n",
    "    #lower profile\n",
    "    P1 = oTG.CreatePoint2d(0, 0)\n",
    "    P2 = oTG.CreatePoint2d(-0.07, 0)\n",
    "    P3 = oTG.CreatePoint2d(-0.07, 1.65)\n",
    "    P4 = oTG.CreatePoint2d(0.0809, 2.4259)\n",
    "    P5 = oTG.CreatePoint2d(.5116, 3.0886)\n",
    "    P6 = oTG.CreatePoint2d(3.5480, 6.23)\n",
    "    P7 = oTG.CreatePoint2d(4.1073, 7.7240)\n",
    "    P8 = oTG.CreatePoint2d(3.3959, 9.1518)\n",
    "    P9 = oTG.CreatePoint2d(-.1809, 12.1546)\n",
    "    P10 = oTG.CreatePoint2d(-.8824 , 13.3473)\n",
    "    P11 = oTG.CreatePoint2d(-.6757, 14.7155)\n",
    "    P12 = oTG.CreatePoint2d(-.3060, 15.4075)\n",
    "    P13 = oTG.CreatePoint2d(-.1299, 15.8642)\n",
    "    P14 = oTG.CreatePoint2d(-0.07, 16.35)\n",
    "    P15 = oTG.CreatePoint2d(-0.07, 17)\n",
    "    P16 = oTG.CreatePoint2d(0, 17)\n",
    "    #upper profile\n",
    "    P17 = oTG.CreatePoint2d(0, 16.35)\n",
    "    P18 = oTG.CreatePoint2d(-0.0620, 15.8472)   \n",
    "    P19 = oTG.CreatePoint2d(-.2443, 15.3745)\n",
    "    P20 = oTG.CreatePoint2d(-.6140, 14.6825)\n",
    "    P21 = oTG.CreatePoint2d(-.8137, 13.3606)\n",
    "    P22 = oTG.CreatePoint2d(-.1359, 12.2082)\n",
    "    P23 = oTG.CreatePoint2d(3.4409 , 9.2054)\n",
    "    P24 = oTG.CreatePoint2d(4.1772, 7.7276)\n",
    "    P25 = oTG.CreatePoint2d(3.5984, 6.1814)\n",
    "    P26 = oTG.CreatePoint2d(.5620, 3.04)\n",
    "    P27 = oTG.CreatePoint2d(.1458 , 2.3996)\n",
    "    P28 = oTG.CreatePoint2d(0, 1.65)\n",
    "    \n",
    "    oArc = oSketch.SketchArcs\n",
    "    oLines = oSketch.SketchLines\n",
    "\n",
    "    oLines1 = oLines.AddByTwoPoints(P1, P2)\n",
    "    oLines2 = oLines.AddByTwoPoints(oLines1.EndSketchPoint, P3)\n",
    "    oArc1 = oArc.AddByThreePoints(oLines2.EndSketchPoint, P4, P5)\n",
    "    oLines3 = oLines.AddByTwoPoints(oArc1.StartSketchPoint, P6)\n",
    "    oArc2 = oArc.AddByThreePoints(oLines3.EndSketchPoint, P7, P8)\n",
    "    oLines4 = oLines.AddByTwoPoints(oArc2.EndSketchPoint, P9)\n",
    "    oArc3 = oArc.AddByThreePoints(oLines4.EndSketchPoint, P10, P11)\n",
    "    oLines5 = oLines.AddByTwoPoints(oArc3.StartSketchPoint, P12)\n",
    "    oArc4 = oArc.AddByThreePoints(oLines5.EndSketchPoint, P13, P14)\n",
    "    oLines6 = oLines.AddByTwoPoints(oArc4.EndSketchPoint, P15)\n",
    "    oLines7 = oLines.AddByTwoPoints(oLines6.EndSketchPoint, P16)\n",
    "    oLines8 = oLines.AddByTwoPoints(oLines7.EndSketchPoint, P17)\n",
    "    oArc5 = oArc.AddByThreePoints(oLines8.EndSketchPoint, P18, P19)\n",
    "    oLines9 = oLines.AddByTwoPoints(oArc5.StartSketchPoint, P20)\n",
    "    oArc6 = oArc.AddByThreePoints(oLines9.EndSketchPoint, P21, P22)\n",
    "    oLines10 = oLines.AddByTwoPoints(oArc6.EndSketchPoint, P23)\n",
    "    oArc7 = oArc.AddByThreePoints(oLines10.EndSketchPoint, P24, P25)\n",
    "    oLines11 = oLines.AddByTwoPoints(oArc7.StartSketchPoint, P26)\n",
    "    oArc8 = oArc.AddByThreePoints(oLines11.EndSketchPoint, P27, P28)\n",
    "    oLines12 = oLines.AddByTwoPoints(oArc8.EndSketchPoint, oLines1.StartSketchPoint)\n",
    "    rotate(oSketch, oApp, 90)\n",
    "    oProfile = oSketch.Profiles.AddForSolid()\n",
    "    oExtFeature = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, l, 20995, 20481)\n",
    "\n",
    "    oApp.ActiveView.GoHome()\n",
    "    \n",
    "    num_notches = int((l-1)/50) + 1\n",
    "    division_len = (l-1)/num_notches\n",
    "\n",
    "#making notches in the rod\n",
    "    oFace1 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(12)\n",
    "    oEdge1 = oFace1.Edges.Item(1)\n",
    "    oVertex1 = oEdge1.StartVertex\n",
    "    oSketch1 = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(oFace1, oEdge1, True, True, oVertex1)\n",
    "    for i in range(num_notches):\n",
    "        x, y = .5 + i*division_len, .36\n",
    "        centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 2)\n",
    "        draw_sketch(centre, p1, p2, p3, p4, oSketch1)\n",
    "    x, y = l-.5, .36\n",
    "    centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 2)\n",
    "    draw_sketch(centre, p1, p2, p3, p4, oSketch1)\n",
    "\n",
    "    oFace2 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(20)\n",
    "    oEdge2 = oFace2.Edges.Item(2)\n",
    "    oVertex2 = oEdge2.StartVertex\n",
    "    oSketch2 = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(oFace2, oEdge2, True, False, oVertex2)\n",
    "    for i in range(num_notches):\n",
    "        x, y = .5 + i*division_len, .36\n",
    "        centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 3)\n",
    "        draw_sketch(centre, p1, p2, p3, p4, oSketch2)\n",
    "    x, y = l-.5, .36\n",
    "    centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 3)\n",
    "    draw_sketch(centre, p1, p2, p3, p4, oSketch2)\n",
    "\n",
    "    solid_profile1 = oSketch2.Profiles.AddforSolid()\n",
    "    ext_solid_def1 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def1.SetDistanceExtent(0.07, 20994)\n",
    "\n",
    "    solid_profile1 = oSketch1.Profiles.AddforSolid()\n",
    "    ext_solid_def2 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def2.SetDistanceExtent(0.07, 20994)\n",
    "\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def1)\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def2)\n",
    "\n",
    "    try:\n",
    "        f = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(k)\n",
    "        e = f.Edges.Item(1)\n",
    "        oVertex2 = e.StartVertex\n",
    "        s = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(f, e, True, True, oVertex2)\n",
    "        s.Name = f\"Sketch-unfold-{k}\"\n",
    "    except:\n",
    "        print(f\"didn't work for {k}\")\n",
    "    #k=8, 9, 10, 22, 23, 49, 52, 5, 61\n",
    "\n",
    "#total faces is equal to 70\n",
    "# i = 2, 10, 20, 12\n",
    "#height_input = float(input(\"Enter height: \"))\n",
    "length = 147\n",
    "for i in range(1,100):\n",
    "    combiner(length, i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import win32com.client as wc\n",
    "\n",
    "def node_sketch(x, y, oTG, pw):\n",
    "    p = (-1)**pw\n",
    "    centre = oTG.CreatePoint2d(p*x, -y)\n",
    "    p1 = oTG.CreatePoint2d(p*(x-.36), -(y-.36))\n",
    "    p2 = oTG.CreatePoint2d(p*(x-.16), -(y-.16))\n",
    "    p3 = oTG.CreatePoint2d(p*(x+.16), -(y-.16))\n",
    "    p4 = oTG.CreatePoint2d(p*(x+.36), -(y-.36))\n",
    "    return centre, p1, p2, p3, p4\n",
    "def draw_sketch(centre, p1, p2, p3, p4, oSketch):\n",
    "    oSketch.SketchLines.AddAsTwoPointCenteredRectangle(centre, p2)\n",
    "    oLines1 = oSketch.SketchLines.AddByTwoPoints(p1, p2)\n",
    "    oLines2 = oSketch.SketchLines.AddByTwoPoints(oLines1.EndSketchPoint, p3)\n",
    "    oLines3 = oSketch.SketchLines.AddByTwoPoints(oLines2.EndSketchPoint, p4)\n",
    "    oLines4 = oSketch.SketchLines.AddByTwoPoints(oLines3.EndSketchPoint, oLines1.StartSketchPoint)\n",
    "def rotate(Sketch, oApp, angle):\n",
    "    objCollection = oApp.TransientObjects.CreateObjectCollection()\n",
    "    angle = angle * (3.141592653589793 / 180)\n",
    "    for line in Sketch.SketchLines:\n",
    "        objCollection.Add(line)\n",
    "    for line in Sketch.SketchArcs:\n",
    "        objCollection.Add(line)\n",
    "    Sketch.RotateSketchObjects(objCollection, oApp.TransientGeometry.CreatePoint2d(0, 0), angle)\n",
    "\n",
    "def combiner(l, k):\n",
    "    oApp = wc.GetActiveObject('Inventor.Application')\n",
    "    oPartDoc = oApp.Documents.Add(12290, oApp.FileManager.GetTemplateFile(12290, 8962, 9729, \"{9C464203-9BAE-11D3-8BAD-0060B0CE6BB4}\"))\n",
    "    oSketch = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(3))\n",
    "    oTG = oApp.TransientGeometry\n",
    "\n",
    "#draing the rod with curves\n",
    "    #lower profile\n",
    "    P1 = oTG.CreatePoint2d(0, 0)\n",
    "    P2 = oTG.CreatePoint2d(-0.07, 0)\n",
    "    P3 = oTG.CreatePoint2d(-0.07, 1.65)\n",
    "    P4 = oTG.CreatePoint2d(0.0809, 2.4259)\n",
    "    P5 = oTG.CreatePoint2d(.5116, 3.0886)\n",
    "    P6 = oTG.CreatePoint2d(3.5480, 6.23)\n",
    "    P7 = oTG.CreatePoint2d(4.1073, 7.7240)\n",
    "    P8 = oTG.CreatePoint2d(3.3959, 9.1518)\n",
    "    P9 = oTG.CreatePoint2d(-.1809, 12.1546)\n",
    "    P10 = oTG.CreatePoint2d(-.8824 , 13.3473)\n",
    "    P11 = oTG.CreatePoint2d(-.6757, 14.7155)\n",
    "    P12 = oTG.CreatePoint2d(-.3060, 15.4075)\n",
    "    P13 = oTG.CreatePoint2d(-.1299, 15.8642)\n",
    "    P14 = oTG.CreatePoint2d(-0.07, 16.35)\n",
    "    P15 = oTG.CreatePoint2d(-0.07, 17)\n",
    "    P16 = oTG.CreatePoint2d(0, 17)\n",
    "    #upper profile\n",
    "    P17 = oTG.CreatePoint2d(0, 16.35)\n",
    "    P18 = oTG.CreatePoint2d(-0.0620, 15.8472)   \n",
    "    P19 = oTG.CreatePoint2d(-.2443, 15.3745)\n",
    "    P20 = oTG.CreatePoint2d(-.6140, 14.6825)\n",
    "    P21 = oTG.CreatePoint2d(-.8137, 13.3606)\n",
    "    P22 = oTG.CreatePoint2d(-.1359, 12.2082)\n",
    "    P23 = oTG.CreatePoint2d(3.4409 , 9.2054)\n",
    "    P24 = oTG.CreatePoint2d(4.1772, 7.7276)\n",
    "    P25 = oTG.CreatePoint2d(3.5984, 6.1814)\n",
    "    P26 = oTG.CreatePoint2d(.5620, 3.04)\n",
    "    P27 = oTG.CreatePoint2d(.1458 , 2.3996)\n",
    "    P28 = oTG.CreatePoint2d(0, 1.65)\n",
    "    \n",
    "    oArc = oSketch.SketchArcs\n",
    "    oLines = oSketch.SketchLines\n",
    "\n",
    "    oLines1 = oLines.AddByTwoPoints(P1, P2)\n",
    "    oLines2 = oLines.AddByTwoPoints(oLines1.EndSketchPoint, P3)\n",
    "    oArc1 = oArc.AddByThreePoints(oLines2.EndSketchPoint, P4, P5)\n",
    "    oLines3 = oLines.AddByTwoPoints(oArc1.StartSketchPoint, P6)\n",
    "    oArc2 = oArc.AddByThreePoints(oLines3.EndSketchPoint, P7, P8)\n",
    "    oLines4 = oLines.AddByTwoPoints(oArc2.EndSketchPoint, P9)\n",
    "    oArc3 = oArc.AddByThreePoints(oLines4.EndSketchPoint, P10, P11)\n",
    "    oLines5 = oLines.AddByTwoPoints(oArc3.StartSketchPoint, P12)\n",
    "    oArc4 = oArc.AddByThreePoints(oLines5.EndSketchPoint, P13, P14)\n",
    "    oLines6 = oLines.AddByTwoPoints(oArc4.EndSketchPoint, P15)\n",
    "    oLines7 = oLines.AddByTwoPoints(oLines6.EndSketchPoint, P16)\n",
    "    oLines8 = oLines.AddByTwoPoints(oLines7.EndSketchPoint, P17)\n",
    "    oArc5 = oArc.AddByThreePoints(oLines8.EndSketchPoint, P18, P19)\n",
    "    oLines9 = oLines.AddByTwoPoints(oArc5.StartSketchPoint, P20)\n",
    "    oArc6 = oArc.AddByThreePoints(oLines9.EndSketchPoint, P21, P22)\n",
    "    oLines10 = oLines.AddByTwoPoints(oArc6.EndSketchPoint, P23)\n",
    "    oArc7 = oArc.AddByThreePoints(oLines10.EndSketchPoint, P24, P25)\n",
    "    oLines11 = oLines.AddByTwoPoints(oArc7.StartSketchPoint, P26)\n",
    "    oArc8 = oArc.AddByThreePoints(oLines11.EndSketchPoint, P27, P28)\n",
    "    oLines12 = oLines.AddByTwoPoints(oArc8.EndSketchPoint, oLines1.StartSketchPoint)\n",
    "    rotate(oSketch, oApp, 90)\n",
    "    oProfile = oSketch.Profiles.AddForSolid()\n",
    "    oExtFeature = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, l, 20995, 20481)\n",
    "\n",
    "    oApp.ActiveView.GoHome()\n",
    "    \n",
    "    num_notches = int((l-1)/50) + 1\n",
    "    division_len = (l-1)/num_notches\n",
    "\n",
    "#making notches in the rod\n",
    "    oFace1 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(12)\n",
    "    oEdge1 = oFace1.Edges.Item(1)\n",
    "    oVertex1 = oEdge1.StartVertex\n",
    "    oSketch1 = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(oFace1, oEdge1, True, True, oVertex1)\n",
    "    for i in range(num_notches):\n",
    "        x, y = .5 + i*division_len, .36\n",
    "        centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 2)\n",
    "        draw_sketch(centre, p1, p2, p3, p4, oSketch1)\n",
    "    x, y = l-.5, .36\n",
    "    centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 2)\n",
    "    draw_sketch(centre, p1, p2, p3, p4, oSketch1)\n",
    "\n",
    "    oFace2 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(20)\n",
    "    oEdge2 = oFace2.Edges.Item(2)\n",
    "    oVertex2 = oEdge2.StartVertex\n",
    "    oSketch2 = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(oFace2, oEdge2, True, False, oVertex2)\n",
    "    for i in range(num_notches):\n",
    "        x, y = .5 + i*division_len, .36\n",
    "        centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 3)\n",
    "        draw_sketch(centre, p1, p2, p3, p4, oSketch2)\n",
    "    x, y = l-.5, .36\n",
    "    centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 3)\n",
    "    draw_sketch(centre, p1, p2, p3, p4, oSketch2)\n",
    "\n",
    "    solid_profile1 = oSketch2.Profiles.AddforSolid()\n",
    "    ext_solid_def1 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def1.SetDistanceExtent(0.07, 20994)\n",
    "\n",
    "    solid_profile1 = oSketch1.Profiles.AddforSolid()\n",
    "    ext_solid_def2 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def2.SetDistanceExtent(0.07, 20994)\n",
    "\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def1)\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def2)\n",
    "\n",
    "    try:\n",
    "        f = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(k)\n",
    "        e = f.Edges.Item(1)\n",
    "        oVertex2 = e.StartVertex\n",
    "        s = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(f, e, True, True, oVertex2)\n",
    "        s.Name = f\"Sketch-unfold-{k}\"\n",
    "    except:\n",
    "        print(f\"didn't work for {k}\")\n",
    "    #k=8, 9, 10, 22, 23, 49, 52, 5, 61\n",
    "\n",
    "#total faces is equal to 70\n",
    "# i = 2, 10, 20, 12\n",
    "#height_input = float(input(\"Enter height: \"))\n",
    "length = 147\n",
    "combiner(length, 52)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import win32com.client as wc\n",
    "\n",
    "def node_sketch(x, y, oTG, pw):\n",
    "    p = (-1)**pw\n",
    "    centre = oTG.CreatePoint2d(p*x, -y)\n",
    "    p1 = oTG.CreatePoint2d(p*(x-.36), -(y-.36))\n",
    "    p2 = oTG.CreatePoint2d(p*(x-.16), -(y-.16))\n",
    "    p3 = oTG.CreatePoint2d(p*(x+.16), -(y-.16))\n",
    "    p4 = oTG.CreatePoint2d(p*(x+.36), -(y-.36))\n",
    "    return centre, p1, p2, p3, p4\n",
    "def draw_sketch(centre, p1, p2, p3, p4, oSketch):\n",
    "    oSketch.SketchLines.AddAsTwoPointCenteredRectangle(centre, p2)\n",
    "    oLines1 = oSketch.SketchLines.AddByTwoPoints(p1, p2)\n",
    "    oLines2 = oSketch.SketchLines.AddByTwoPoints(oLines1.EndSketchPoint, p3)\n",
    "    oLines3 = oSketch.SketchLines.AddByTwoPoints(oLines2.EndSketchPoint, p4)\n",
    "    oLines4 = oSketch.SketchLines.AddByTwoPoints(oLines3.EndSketchPoint, oLines1.StartSketchPoint)\n",
    "\n",
    "def combiner(l):\n",
    "    oApp = wc.GetActiveObject('Inventor.Application')\n",
    "    oPartDoc = oApp.Documents.Add(12290, oApp.FileManager.GetTemplateFile(12290, 8962, 9729, \"{9C464203-9BAE-11D3-8BAD-0060B0CE6BB4}\"))\n",
    "    oSketch = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(3))\n",
    "    oTG = oApp.TransientGeometry\n",
    "\n",
    "#draing the rod with curves\n",
    "\n",
    "    #lower profile\n",
    "    P1 = oTG.CreatePoint2d(0, 0)\n",
    "    P2 = oTG.CreatePoint2d(-0.07, 0)\n",
    "    P3 = oTG.CreatePoint2d(-0.07, 1.65)\n",
    "    P4 = oTG.CreatePoint2d(0.0809, 2.4259)\n",
    "    P5 = oTG.CreatePoint2d(.5116, 3.0886)\n",
    "    P6 = oTG.CreatePoint2d(3.5480, 6.23)\n",
    "    P7 = oTG.CreatePoint2d(4.1073, 7.7240)\n",
    "    P8 = oTG.CreatePoint2d(3.3959, 9.1518)\n",
    "    P9 = oTG.CreatePoint2d(-.1809, 12.1546)\n",
    "    P10 = oTG.CreatePoint2d(-.8824 , 13.3473)\n",
    "    P11 = oTG.CreatePoint2d(-.6757, 14.7155)\n",
    "    P12 = oTG.CreatePoint2d(-.3060, 15.4075)\n",
    "    P13 = oTG.CreatePoint2d(-.1299, 15.8642)\n",
    "    P14 = oTG.CreatePoint2d(-0.07, 16.35)\n",
    "    P15 = oTG.CreatePoint2d(-0.07, 17)\n",
    "    P16 = oTG.CreatePoint2d(0, 17)\n",
    "    #upper profile\n",
    "    P17 = oTG.CreatePoint2d(0, 16.35)\n",
    "    P18 = oTG.CreatePoint2d(-0.0620, 15.8472)   \n",
    "    P19 = oTG.CreatePoint2d(-.2443, 15.3745)\n",
    "    P20 = oTG.CreatePoint2d(-.6140, 14.6825)\n",
    "    P21 = oTG.CreatePoint2d(-.8137, 13.3606)\n",
    "    P22 = oTG.CreatePoint2d(-.1359, 12.2082)\n",
    "    P23 = oTG.CreatePoint2d(3.4409 , 9.2054)\n",
    "    P24 = oTG.CreatePoint2d(4.1772, 7.7276)\n",
    "    P25 = oTG.CreatePoint2d(3.5984, 6.1814)\n",
    "    P26 = oTG.CreatePoint2d(.5620, 3.04)\n",
    "    P27 = oTG.CreatePoint2d(.1458 , 2.3996)\n",
    "    P28 = oTG.CreatePoint2d(0, 1.65)\n",
    "    \n",
    "    oArc = oSketch.SketchArcs\n",
    "    oLines = oSketch.SketchLines\n",
    "\n",
    "    oLines1 = oLines.AddByTwoPoints(P1, P2)\n",
    "    oLines2 = oLines.AddByTwoPoints(oLines1.EndSketchPoint, P3)\n",
    "    oArc1 = oArc.AddByThreePoints(oLines2.EndSketchPoint, P4, P5)\n",
    "    oLines3 = oLines.AddByTwoPoints(oArc1.StartSketchPoint, P6)\n",
    "    oArc2 = oArc.AddByThreePoints(oLines3.EndSketchPoint, P7, P8)\n",
    "    oLines4 = oLines.AddByTwoPoints(oArc2.EndSketchPoint, P9)\n",
    "    oArc3 = oArc.AddByThreePoints(oLines4.EndSketchPoint, P10, P11)\n",
    "    oLines5 = oLines.AddByTwoPoints(oArc3.StartSketchPoint, P12)\n",
    "    oArc4 = oArc.AddByThreePoints(oLines5.EndSketchPoint, P13, P14)\n",
    "    oLines6 = oLines.AddByTwoPoints(oArc4.EndSketchPoint, P15)\n",
    "    oLines7 = oLines.AddByTwoPoints(oLines6.EndSketchPoint, P16)\n",
    "    oLines8 = oLines.AddByTwoPoints(oLines7.EndSketchPoint, P17)\n",
    "    oArc5 = oArc.AddByThreePoints(oLines8.EndSketchPoint, P18, P19)\n",
    "    oLines9 = oLines.AddByTwoPoints(oArc5.StartSketchPoint, P20)\n",
    "    oArc6 = oArc.AddByThreePoints(oLines9.EndSketchPoint, P21, P22)\n",
    "    oLines10 = oLines.AddByTwoPoints(oArc6.EndSketchPoint, P23)\n",
    "    oArc7 = oArc.AddByThreePoints(oLines10.EndSketchPoint, P24, P25)\n",
    "    oLines11 = oLines.AddByTwoPoints(oArc7.StartSketchPoint, P26)\n",
    "    oArc8 = oArc.AddByThreePoints(oLines11.EndSketchPoint, P27, P28)\n",
    "    oLines12 = oLines.AddByTwoPoints(oArc8.EndSketchPoint, oLines1.StartSketchPoint)\n",
    "\n",
    "    oProfile = oSketch.Profiles.AddForSolid()\n",
    "    oExtFeature = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.AddByDistanceExtent(oProfile, l, 20995, 20481)\n",
    "\n",
    "    oApp.ActiveView.GoHome()\n",
    "    \n",
    "    num_notches = int((l-1)/50) + 1\n",
    "    division_len = (l-1)/num_notches\n",
    "\n",
    "#making notches in the rod\n",
    "\n",
    "    \"\"\"oFace1 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(12)\n",
    "    oEdge1 = oFace1.Edges.Item(1)\n",
    "    oVertex1 = oEdge1.StartVertex\n",
    "    oSketch1 = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(oFace1, oEdge1, True, True, oVertex1)\n",
    "    for i in range(num_notches):\n",
    "        x, y = .5 + i*division_len, .36\n",
    "        centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 2)\n",
    "        draw_sketch(centre, p1, p2, p3, p4, oSketch1)\n",
    "    x, y = l-.5, .36\n",
    "    centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 2)\n",
    "    draw_sketch(centre, p1, p2, p3, p4, oSketch1)\n",
    "\n",
    "    oFace2 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(20)\n",
    "    oEdge2 = oFace2.Edges.Item(2)\n",
    "    oVertex2 = oEdge2.StartVertex\n",
    "    oSketch2 = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(oFace2, oEdge2, True, False, oVertex2)\n",
    "    for i in range(num_notches):\n",
    "        x, y = .5 + i*division_len, .36\n",
    "        centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 3)\n",
    "        draw_sketch(centre, p1, p2, p3, p4, oSketch2)\n",
    "    x, y = l-.5, .36\n",
    "    centre, p1, p2, p3, p4 = node_sketch(x, y, oTG, 3)\n",
    "    draw_sketch(centre, p1, p2, p3, p4, oSketch2)\n",
    "\n",
    "    solid_profile1 = oSketch2.Profiles.AddforSolid()\n",
    "    ext_solid_def1 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def1.SetDistanceExtent(0.07, 20994)\n",
    "\n",
    "    solid_profile1 = oSketch1.Profiles.AddforSolid()\n",
    "    ext_solid_def2 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def2.SetDistanceExtent(0.07, 20994)\n",
    "\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def1)\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def2)\"\"\"\n",
    "\n",
    "#cutting the rod to fit the curved shape\n",
    "\n",
    "    z0, x0 = l/2 + 76.5, 320\n",
    "    sketch_xz = oPartDoc.ComponentDefinition.Sketches.Add(oPartDoc.ComponentDefinition.WorkPlanes.Item(2))\n",
    "    sketch_xz.SketchCircles.AddByCenterRadius(oTG.CreatePoint2d(-x0, -z0), 372.9)\n",
    "    sketch_xz.SketchCircles.AddByCenterRadius(oTG.CreatePoint2d(-x0, -z0), 500)\n",
    "    solid_profile1 = sketch_xz.Profiles.AddforSolid()\n",
    "    ext_solid_def1 = oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.CreateExtrudeDefinition(solid_profile1, 20482)\n",
    "    ext_solid_def1.SetDistanceExtent(17, 20993)\n",
    "    oPartDoc.ComponentDefinition.Features.ExtrudeFeatures.Add(ext_solid_def1)\n",
    "\n",
    "    \"\"\"try:\n",
    "        f = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(k)\n",
    "        e = f.Edges.Item(1)\n",
    "        oVertex2 = e.StartVertex\n",
    "        s = oPartDoc.ComponentDefinition.Sketches.AddWithOrientation(f, e, True, True, oVertex2)\n",
    "        s.Name = f\"Sketch-unfold-{k}\"\n",
    "    except:\n",
    "        print(f\"didn't work for {k}\")\n",
    "    #k = 2, 10, 13, 21\"\"\"\n",
    "    \n",
    "\n",
    "#unfolding\n",
    "    allFaces = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces\n",
    "    oFace1 = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).Faces.Item(20)\n",
    "    unfoldFeatures = oPartDoc.ComponentDefinition.Features.UnfoldFeatures.Add(oFace1)\n",
    "    oPartDoc.ComponentDefinition.Unfold()\n",
    "\n",
    "\n",
    "\n",
    "# i = 2, 10, 20, 12\n",
    "#height_input = float(input(\"Enter height: \"))\n",
    "length = 130\n",
    "combiner(length)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
